CREATE TABLE IF NOT EXISTS webhook_delivery_attempts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subscription_id integer NOT NULL REFERENCES webhook_subscriptions(id) ON DELETE RESTRICT,
  event_id uuid NOT NULL,
  event_type varchar(128) NOT NULL,
  payload jsonb NOT NULL,
  destination_url text NOT NULL,
  status varchar(16) NOT NULL DEFAULT 'shadow',
  attempt_count integer NOT NULL DEFAULT 0,
  max_attempts integer NOT NULL DEFAULT 3,
  next_retry_at timestamptz NOT NULL DEFAULT now(),
  claimed_at timestamptz,
  delivered_at timestamptz,
  last_response_code integer,
  idempotency_key varchar(160) NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT webhook_delivery_attempt_status_check
    CHECK (status IN ('shadow', 'pending', 'processing', 'retrying', 'delivered', 'dead')),
  CONSTRAINT webhook_delivery_attempt_count_check CHECK (attempt_count >= 0),
  CONSTRAINT webhook_delivery_attempt_max_attempts_check CHECK (max_attempts > 0),
  CONSTRAINT webhook_delivery_attempt_processing_claim_check
    CHECK ((status = 'processing' AND claimed_at IS NOT NULL) OR status <> 'processing')
);

DO $$
BEGIN
  ALTER TABLE webhook_delivery_attempts
    ADD CONSTRAINT webhook_delivery_attempt_status_check
    CHECK (status IN ('shadow', 'pending', 'processing', 'retrying', 'delivered', 'dead'));
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER TABLE webhook_delivery_attempts
    ADD CONSTRAINT webhook_delivery_attempt_count_check CHECK (attempt_count >= 0);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER TABLE webhook_delivery_attempts
    ADD CONSTRAINT webhook_delivery_attempt_max_attempts_check CHECK (max_attempts > 0);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER TABLE webhook_delivery_attempts
    ADD CONSTRAINT webhook_delivery_attempt_processing_claim_check
    CHECK ((status = 'processing' AND claimed_at IS NOT NULL) OR status <> 'processing');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS idx_webhook_delivery_attempts_claim
  ON webhook_delivery_attempts (next_retry_at, id)
  WHERE status IN ('pending', 'retrying');

CREATE INDEX IF NOT EXISTS idx_webhook_delivery_attempts_event
  ON webhook_delivery_attempts (subscription_id, event_id);

CREATE INDEX IF NOT EXISTS idx_webhook_delivery_attempts_shadow
  ON webhook_delivery_attempts (created_at, id)
  WHERE status = 'shadow';
