import { Link } from "expo-router";
import { useState } from "react";
import { Pressable, ScrollView, Text, TextInput, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { trpc } from "@/lib/trpc";

export default function AuditExportVerificationScreen() {
  const [receiptId, setReceiptId] = useState("");
  const [submitted, setSubmitted] = useState("");
  const verification = trpc.system.verifyAuditInvestigationExportReceipt.useQuery({ eventId: submitted }, { enabled: Boolean(submitted), retry: false });
  const result = verification.data;
  return <ScreenContainer className="p-5"><ScrollView contentContainerStyle={{ gap: 16, paddingBottom: 32 }}><Link href="/(tabs)/profile" asChild><Pressable><Text className="text-sm font-semibold text-primary">‹ Profile</Text></Pressable></Link><View><Text className="text-2xl font-bold text-foreground">Audit export verification</Text><Text className="mt-2 text-sm leading-5 text-muted">Read-only verification checks whether a report receipt remains in the server hash chain. It does not expose report content or security event payloads beyond the receipt.</Text></View><View className="rounded-3xl border border-border bg-surface p-5"><Text className="text-sm font-semibold text-foreground">Receipt identifier</Text><TextInput value={receiptId} onChangeText={setReceiptId} placeholder="Paste UUID receipt identifier" autoCapitalize="none" placeholderTextColor="#687076" className="mt-3 rounded-xl border border-border px-3 py-3 text-sm text-foreground" /><Pressable disabled={receiptId.trim().length < 36} onPress={() => setSubmitted(receiptId.trim())} style={({ pressed }) => [{ opacity: receiptId.trim().length < 36 ? 0.45 : pressed ? 0.8 : 1 }]}><View className="mt-3 rounded-xl bg-foreground p-3"><Text className="text-center text-sm font-semibold text-background">Verify receipt</Text></View></Pressable></View>{verification.isFetching ? <Text className="text-sm text-muted">Verifying chain receipt…</Text> : null}{verification.error ? <View className="rounded-2xl border border-error bg-error/10 p-4"><Text className="text-sm font-semibold text-error">Verification unavailable</Text><Text className="mt-1 text-xs text-error">{verification.error.message}</Text></View> : null}{result ? <View className={`rounded-3xl border p-5 ${result.valid ? "border-success bg-success/10" : "border-error bg-error/10"}`}><Text className={`text-lg font-bold ${result.valid ? "text-success" : "text-error"}`}>{result.valid ? "Receipt integrity verified" : "Receipt could not be verified"}</Text><Text className="mt-2 text-sm leading-5 text-foreground">{result.reason ?? "The receipt event is present and the full audit chain currently validates."}</Text>{result.receipt ? <View className="mt-4 gap-1"><Text className="text-xs text-muted">Issued: {new Date(result.receipt.occurredAt).toLocaleString()}</Text><Text className="text-xs text-muted">Event hash: {result.receipt.eventHash.slice(0, 24)}…</Text><Text className="text-xs text-muted">Signature: {result.receipt.signed ? "HMAC verified by configured server key" : "Hash chain only; server HMAC is not configured"}</Text></View> : null}</View> : null}</ScrollView></ScreenContainer>;
}
