import { useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, Text, View } from "react-native";
import * as DocumentPicker from "expo-document-picker";
import * as FileSystem from "expo-file-system/legacy";
import { Stack } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { parseAndVerifyDiagnosticExportReceipt, type DiagnosticExportReceipt } from "@/lib/stakeholder-export-receipt-crypto";

async function readPickedReceipt(asset: DocumentPicker.DocumentPickerAsset) { if (asset.file) return asset.file.text(); return FileSystem.readAsStringAsync(asset.uri, { encoding: FileSystem.EncodingType.UTF8 }); }
export default function DiagnosticReceiptVerificationScreen() { const [checking, setChecking] = useState(false); const [result, setResult] = useState<{ valid: boolean; message: string; receipt?: DiagnosticExportReceipt } | null>(null); const verifyReceipt = async () => { setChecking(true); setResult(null); try { const picked = await DocumentPicker.getDocumentAsync({ type: ["application/json", "text/json"], copyToCacheDirectory: true, multiple: false }); if (picked.canceled || !picked.assets?.[0]) return; setResult(await parseAndVerifyDiagnosticExportReceipt(await readPickedReceipt(picked.assets[0]))); } catch (error) { setResult({ valid: false, message: error instanceof Error ? error.message : "The receipt could not be opened." }); } finally { setChecking(false); } }; return <ScreenContainer className="p-5"><Stack.Screen options={{ title: "Verify diagnostic receipt" }} /><ScrollView contentContainerStyle={{ paddingBottom: 32 }}><Text className="text-2xl font-bold text-foreground">Verify diagnostic receipt</Text><Text className="mt-2 text-sm leading-5 text-muted">Select a downloaded receipt to validate its device signature and public-key fingerprint. To confirm that it belongs to a package, compare its package digest with the corresponding exported package.</Text><Pressable onPress={() => void verifyReceipt()} disabled={checking} style={{ opacity: checking ? 0.55 : 1 }}><View className="mt-6 rounded-2xl bg-primary p-4"><Text className="text-center font-semibold text-white">{checking ? "Verifying receipt…" : "Select receipt file"}</Text></View></Pressable>{checking ? <ActivityIndicator className="mt-5" /> : null}{result ? <View className={`mt-6 rounded-2xl border p-4 ${result.valid ? "border-success bg-background" : "border-error bg-background"}`}><Text className={`font-bold ${result.valid ? "text-success" : "text-error"}`}>{result.valid ? "Receipt verified" : "Receipt not verified"}</Text><Text className="mt-2 text-sm leading-5 text-foreground">{result.message}</Text>{result.receipt ? <View className="mt-4 gap-1"><Text className="text-xs text-muted">Receipt ID: {result.receipt.receiptId}</Text><Text className="text-xs text-muted">Exported: {new Date(result.receipt.exportedAt).toLocaleString()}</Text><Text className="text-xs text-muted">Signer: {result.receipt.signer.fingerprint}</Text><Text className="text-xs text-muted">Package digest: {result.receipt.packageSha256}</Text></View> : null}</View> : null}</ScrollView></ScreenContainer>; }
