import { useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, Text, TextInput, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { trpc } from "@/lib/trpc";

type GatewayField = "PAYMENT_GATEWAY_ACTIVE_PROVIDER" | "PAYMENT_GATEWAY_PUBLIC_BASE_URL" | "PAYSTACK_SECRET_KEY" | "FLUTTERWAVE_WEBHOOK_SECRET_HASH" | "FLUTTERWAVE_SECRET_KEY";
const fields: { key: GatewayField; label: string; secret?: boolean; placeholder: string }[] = [
  { key: "PAYMENT_GATEWAY_ACTIVE_PROVIDER", label: "Active provider", placeholder: "paystack or flutterwave" },
  { key: "PAYMENT_GATEWAY_PUBLIC_BASE_URL", label: "Public HTTPS origin", placeholder: "https://land.example.gov.ng" },
  { key: "PAYSTACK_SECRET_KEY", label: "Paystack secret key", secret: true, placeholder: "Enter replacement key" },
  { key: "FLUTTERWAVE_WEBHOOK_SECRET_HASH", label: "Flutterwave webhook secret hash", secret: true, placeholder: "Enter replacement hash" },
  { key: "FLUTTERWAVE_SECRET_KEY", label: "Flutterwave secret key", secret: true, placeholder: "Enter replacement key" },
];

export default function PaymentGatewaySettingsScreen() {
  const utils = trpc.useUtils(); const settings = trpc.integrationSettings.status.useQuery(); const activation = trpc.paymentOperations.gatewayActivation.useQuery({}, { retry: false });
  const [values, setValues] = useState<Partial<Record<GatewayField, string>>>({}); const [feedback, setFeedback] = useState<string | null>(null);
  const secureStorageReady = Boolean(settings.data?.secureStorageAvailable); const provider = activation.data?.provider; const fieldStatus = new Map(settings.data?.fields.map((field) => [field.field, field]));
  const save = trpc.integrationSettings.save.useMutation({ onSuccess: async () => { setValues({}); setFeedback("Gateway settings saved. Stored secrets remain redacted."); await Promise.all([utils.integrationSettings.status.invalidate(), utils.paymentOperations.gatewayActivation.invalidate()]); }, onError: (error) => setFeedback(error.message || "Gateway settings could not be saved.") });
  const guide = provider === "paystack" ? ["Open Paystack Dashboard → Settings → API Keys & Webhooks.", "Paste the callback URL shown above as the webhook URL and save.", "Send an authorised test event; confirm it appears as a signed delivery before accepting any settlement."] : provider === "flutterwave" ? ["Open Flutterwave Dashboard → Settings → Webhooks.", "Paste the callback URL shown above and set the same secret hash saved here.", "Send an authorised test event; confirm server-side transaction verification before settlement."] : ["Choose paystack or flutterwave as the active provider.", "Enter a public HTTPS origin with no path, then save server credentials.", "Return here to copy the generated provider-specific callback URL."];
  return <ScreenContainer className="bg-background"><ScrollView contentContainerStyle={{ padding: 20, gap: 16 }} keyboardShouldPersistTaps="handled">
    <View className="rounded-[28px] bg-surface p-5"><Text className="text-sm text-muted">Administrator payment controls</Text><Text className="mt-2 text-3xl font-bold text-foreground">Gateway settings</Text><Text className="mt-2 text-sm leading-5 text-muted">Secrets are encrypted server-side when secure storage is available and are never displayed after saving.</Text></View>
    <View className={`rounded-3xl border p-5 ${activation.data?.ready ? "border-success bg-success/5" : "border-warning bg-warning/5"}`}><Text className={`font-semibold ${activation.data?.ready ? "text-success" : "text-warning"}`}>{activation.data?.ready ? "Callback configuration ready" : "Settlement connection unavailable"}</Text><Text className="mt-2 text-sm leading-5 text-muted">{activation.data?.callbackUrl ? `Callback URL: ${activation.data.callbackUrl}` : activation.data?.reason ?? "Loading activation status…"}</Text><Text className="mt-2 text-xs leading-4 text-muted">Ready configuration never proves settlement. A signed delivery must pass independent transaction re-verification.</Text></View>
    <View className="rounded-3xl border border-border bg-surface p-5"><Text className="text-lg font-semibold text-foreground">Callback registration guide</Text><Text className="mt-2 text-sm text-muted">{provider ? `Selected provider: ${provider === "paystack" ? "Paystack" : "Flutterwave"}.` : "Provider not selected."}</Text>{guide.map((step, index) => <Text key={step} className="mt-3 text-sm leading-5 text-foreground">{index + 1}. {step}</Text>)}</View>
    {!secureStorageReady ? <View className="rounded-3xl border border-warning bg-warning/10 p-5"><Text className="font-semibold text-warning">Secure server storage is required</Text><Text className="mt-2 text-sm text-muted">{settings.data?.reason ?? "Configure the server encryption key before entering gateway credentials."}</Text></View> : null}
    <View className="rounded-3xl border border-border bg-surface p-5"><Text className="text-lg font-semibold text-foreground">Credential status and updates</Text><Text className="mt-2 text-sm leading-5 text-muted">Leave secret fields empty to retain existing values. Provider selection and public origin are non-secret configuration values.</Text><View className="mt-4 gap-3">{fields.map((field) => { const status = fieldStatus.get(field.key); return <View key={field.key} className="rounded-2xl border border-border bg-background p-4"><View className="flex-row justify-between gap-3"><Text className="flex-1 text-sm font-semibold text-foreground">{field.label}</Text><Text className={`text-xs font-semibold ${status?.configured ? "text-success" : "text-warning"}`}>{status?.configured ? "Configured" : "Not configured"}</Text></View><TextInput value={values[field.key] ?? ""} onChangeText={(value) => setValues((current) => ({ ...current, [field.key]: value }))} editable={secureStorageReady && !save.isPending} secureTextEntry={field.secret} autoCapitalize="none" placeholder={field.placeholder} placeholderTextColor="#94A3B8" className="mt-3 rounded-xl border border-border px-3 py-3 text-sm text-foreground" /></View>; })}</View><Pressable disabled={!secureStorageReady || save.isPending} onPress={() => save.mutate(values)} style={({ pressed }) => [{ opacity: !secureStorageReady || save.isPending ? 0.45 : pressed ? 0.82 : 1 }]}><View className="mt-5 rounded-2xl bg-foreground px-4 py-4">{save.isPending ? <ActivityIndicator color="#FFFFFF" /> : <Text className="text-center font-semibold text-background">Save encrypted gateway settings</Text>}</View></Pressable></View>
    {feedback ? <View className={`rounded-2xl border p-4 ${save.isError ? "border-error bg-error/5" : "border-primary bg-primary/5"}`}><Text className="text-sm text-foreground">{feedback}</Text></View> : null}
  </ScrollView></ScreenContainer>;
}
