import * as WebBrowser from "expo-web-browser";
import { Link } from "expo-router";
import { useState } from "react";
import { Alert, Modal, Pressable, ScrollView, Text, TextInput, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { bulkSessionConfirmationPhrase } from "@/lib/keycloak-bulk-revocation";
import { trpc } from "@/lib/trpc";

export default function SecurityIdentityScreen() {
  const status = trpc.system.identitySecurity.useQuery(undefined, { retry: false });
  const revoke = trpc.system.revokeKeycloakSession.useMutation({ onSuccess: () => status.refetch() });
  const bulkRevoke = trpc.system.revokeKeycloakSessionsBulk.useMutation({ onSuccess: () => { setSelection([]); setBulkOpen(false); status.refetch(); } });
  const revokeOther = trpc.system.revokeOtherUserKeycloakSession.useMutation({ onSuccess: () => { setOtherOpen(false); setOtherTarget(null); directory.refetch(); } });
  const [selection, setSelection] = useState<string[]>([]);
  const [bulkOpen, setBulkOpen] = useState(false);
  const [confirmation, setConfirmation] = useState("");
  const [reason, setReason] = useState("");
  const [directorySearch, setDirectorySearch] = useState("");
  const [otherTarget, setOtherTarget] = useState<{ subject: string; username: string; sessionId: string; sourceAddress: string | null } | null>(null);
  const [otherOpen, setOtherOpen] = useState(false);
  const directory = trpc.system.listKeycloakDirectorySessions.useQuery({ search: directorySearch }, { enabled: Boolean(status.data?.canInvestigateOtherUsers && status.data?.externalSessionDirectoryAvailable && directorySearch.trim().length >= 2), retry: false });
  const toggle = (sessionId: string) => setSelection((current) => current.includes(sessionId) ? current.filter((value) => value !== sessionId) : [...current, sessionId]);
  const requestRevocation = (sessionId: string) => Alert.alert("Terminate session?", "This asks the configured Keycloak administrator API to delete the selected identity-provider session. The action is recorded in the security audit trail.", [{ text: "Cancel", style: "cancel" }, { text: "Terminate", style: "destructive", onPress: () => revoke.mutate({ sessionId }) }]);
  const expected = bulkSessionConfirmationPhrase(selection.length);
  const canBulk = selection.length > 0 && confirmation.trim() === expected && reason.trim().length >= 10 && !bulkRevoke.isPending;
  const canRevokeOther = Boolean(otherTarget && confirmation.trim() === "TERMINATE OTHER USER SESSION" && reason.trim().length >= 10 && !revokeOther.isPending);

  return <ScreenContainer className="p-5"><ScrollView contentContainerStyle={{ gap: 16, paddingBottom: 32 }}>
    <Link href="/(tabs)/profile" asChild><Pressable><Text className="text-sm font-semibold text-primary">‹ Profile</Text></Pressable></Link>
    <View><Text className="text-2xl font-bold text-foreground">Active sessions and MFA</Text><Text className="mt-2 text-sm leading-5 text-muted">Passkey enrollment is shown as verified only when the signed identity-provider token reports a WebAuthn/passkey method.</Text></View>
    {status.data?.activeSessions.map((session) => { const verified = session.passkeyStatus === "verified_in_this_session"; const selected = selection.includes(session.sessionId); return <View key={session.sessionId} className="rounded-3xl border border-border bg-surface p-5"><View className="flex-row items-center justify-between gap-3"><Text className="text-lg font-semibold text-foreground">{session.label}</Text><View className={`rounded-full px-3 py-1 ${verified ? "bg-success/15" : "bg-warning/15"}`}><Text className={`text-xs font-bold ${verified ? "text-success" : "text-warning"}`}>{verified ? "Passkey verified" : session.passkeyStatus === "not_reported_by_token" ? "Passkey not reported" : "Local session"}</Text></View></View><Text className="mt-2 text-sm text-muted">Authentication: {session.loginMethod} · {new Date(session.signedInAt).toLocaleString()}</Text>{session.revocable ? <><Pressable onPress={() => toggle(session.sessionId)}><View className={`mt-4 flex-row items-center gap-3 rounded-2xl border p-3 ${selected ? "border-primary bg-primary/10" : "border-border bg-background"}`}><View className={`h-5 w-5 rounded border ${selected ? "border-primary bg-primary" : "border-muted"}`}>{selected ? <Text className="text-center text-xs text-background">✓</Text> : null}</View><Text className="text-sm font-semibold text-foreground">Select for bulk termination</Text></View></Pressable><Pressable disabled={revoke.isPending} onPress={() => requestRevocation(session.sessionId)}><View className="mt-3 rounded-2xl border border-error bg-error/10 p-3"><Text className="text-center text-sm font-semibold text-error">Terminate suspicious session</Text></View></Pressable></> : <Text className="mt-4 text-xs text-muted">Remote session revocation is unavailable until the allowlisted Keycloak administrative API is configured.</Text>}</View>; })}
    {selection.length ? <Pressable onPress={() => { setConfirmation(""); setReason(""); setBulkOpen(true); }}><View className="rounded-2xl border border-error bg-error/10 p-4"><Text className="text-center text-sm font-semibold text-error">Review bulk termination ({selection.length})</Text></View></Pressable> : null}
    {status.data?.canInvestigateOtherUsers ? <View className="rounded-3xl border border-border bg-surface p-5"><Text className="text-lg font-semibold text-foreground">Supervisor session directory</Text>{status.data.externalSessionDirectoryAvailable ? <><Text className="mt-1 text-xs leading-5 text-muted">Search is limited to the configured Keycloak realm. Source addresses are redacted; geography and risk are displayed only when supplied by the approved Keycloak session extension.</Text><TextInput value={directorySearch} onChangeText={setDirectorySearch} placeholder="Search username or subject" placeholderTextColor="#687076" className="mt-4 rounded-xl border border-border px-3 py-3 text-sm text-foreground" />{directory.isFetching ? <Text className="mt-3 text-xs text-muted">Searching Keycloak sessions…</Text> : null}{directory.error ? <Text className="mt-3 text-xs text-error">{directory.error.message}</Text> : null}{directory.data?.sessions.map((session) => <View key={session.sessionId} className="mt-3 rounded-2xl border border-border bg-background p-3"><Text className="text-sm font-semibold text-foreground">{session.username}</Text><Text className="mt-1 text-xs text-muted">Last access: {session.lastAccessAt ? new Date(session.lastAccessAt).toLocaleString() : "not reported"} · Source: {session.sourceAddress ?? "not reported"}</Text><View className="mt-2 flex-row flex-wrap gap-2"><View className={`rounded-full px-2 py-1 ${session.geography ? "bg-primary/10" : "bg-warning/10"}`}><Text className={`text-[11px] font-semibold ${session.geography ? "text-primary" : "text-warning"}`}>Location: {session.geography ?? "not reported"}</Text></View><View className={`rounded-full px-2 py-1 ${session.riskScore === null ? "bg-warning/10" : session.riskScore >= 70 ? "bg-error/10" : "bg-success/10"}`}><Text className={`text-[11px] font-semibold ${session.riskScore === null ? "text-warning" : session.riskScore >= 70 ? "text-error" : "text-success"}`}>Risk: {session.riskScore === null ? "not reported" : `${session.riskScore}/100`}</Text></View></View><Pressable onPress={() => { setOtherTarget(session); setConfirmation(""); setReason(""); setOtherOpen(true); }}><View className="mt-3 rounded-xl border border-error px-3 py-2"><Text className="text-center text-xs font-semibold text-error">Terminate this other-user session</Text></View></Pressable></View>)}</> : <Text className="mt-2 text-sm text-warning">The Keycloak administrative directory is not configured; cross-user sessions remain unavailable and cannot be terminated.</Text>}</View> : null}
    {revoke.error || bulkRevoke.error || revokeOther.error ? <View className="rounded-xl border border-error bg-error/10 p-3"><Text className="text-xs text-error">{revoke.error?.message ?? bulkRevoke.error?.message ?? revokeOther.error?.message}</Text></View> : null}
    {status.data?.accountConsoleUrl ? <Pressable onPress={() => WebBrowser.openBrowserAsync(status.data!.accountConsoleUrl!)}><View className="rounded-2xl bg-foreground p-4"><Text className="text-center font-semibold text-background">Manage MFA in Keycloak</Text></View></Pressable> : <View className="rounded-2xl border border-warning bg-warning/10 p-4"><Text className="text-sm text-warning">Keycloak account console has not been configured.</Text></View>}
  </ScrollView>
  <Modal visible={bulkOpen} transparent animationType="fade" onRequestClose={() => setBulkOpen(false)}><ConfirmationSheet title={`Terminate ${selection.length} sessions`} description="Keycloak processes each remote session independently. Every attempt is recorded in the security audit trail." reason={reason} onReason={setReason} confirmation={confirmation} onConfirmation={setConfirmation} expected={expected} enabled={canBulk} busy={bulkRevoke.isPending} onCancel={() => setBulkOpen(false)} onConfirm={() => bulkRevoke.mutate({ sessionIds: selection, confirmation, reason })} /></Modal>
  <Modal visible={otherOpen} transparent animationType="fade" onRequestClose={() => setOtherOpen(false)}><ConfirmationSheet title={`Terminate ${otherTarget?.username ?? "other user"} session`} description="You are terminating a separately owned Keycloak session. Keycloak ownership was verified before this control was displayed. This action is HMAC-audited." reason={reason} onReason={setReason} confirmation={confirmation} onConfirmation={setConfirmation} expected="TERMINATE OTHER USER SESSION" enabled={canRevokeOther} busy={revokeOther.isPending} onCancel={() => setOtherOpen(false)} onConfirm={() => otherTarget && revokeOther.mutate({ targetSubject: otherTarget.subject, sessionId: otherTarget.sessionId, confirmation: "TERMINATE OTHER USER SESSION", reason })} /></Modal>
  </ScreenContainer>;
}

function ConfirmationSheet({ title, description, reason, onReason, confirmation, onConfirmation, expected, enabled, busy, onCancel, onConfirm }: { title: string; description: string; reason: string; onReason: (value: string) => void; confirmation: string; onConfirmation: (value: string) => void; expected: string; enabled: boolean; busy: boolean; onCancel: () => void; onConfirm: () => void }) { return <View className="flex-1 items-center justify-center bg-black/50 p-5"><View className="w-full max-w-md rounded-3xl bg-background p-5"><Text className="text-xl font-bold text-foreground">{title}</Text><Text className="mt-2 text-sm leading-5 text-muted">{description}</Text><TextInput value={reason} onChangeText={onReason} placeholder="Reason for termination" placeholderTextColor="#687076" className="mt-4 rounded-xl border border-border px-3 py-3 text-sm text-foreground" /><Text className="mt-3 text-xs text-muted">Enter {expected} to confirm.</Text><TextInput value={confirmation} onChangeText={onConfirmation} autoCapitalize="characters" placeholder={expected} placeholderTextColor="#687076" className="mt-2 rounded-xl border border-border px-3 py-3 text-sm text-foreground" /><View className="mt-5 flex-row gap-3"><Pressable onPress={onCancel}><View className="rounded-xl border border-border px-4 py-3"><Text className="font-semibold text-foreground">Cancel</Text></View></Pressable><Pressable disabled={!enabled} onPress={onConfirm} style={({ pressed }) => [{ opacity: enabled ? pressed ? 0.8 : 1 : 0.45 }]}><View className="rounded-xl bg-error px-4 py-3"><Text className="font-semibold text-background">{busy ? "Terminating…" : "Terminate session"}</Text></View></Pressable></View></View></View>; }
