import { router } from "expo-router";
import { ActivityIndicator, Alert, Pressable, StyleSheet, Text, View } from "react-native";
import { useState } from "react";
import { ScreenContainer } from "@/components/screen-container";
import { signInWithPkce } from "@/lib/oidc-session";
const STAGING_ISSUER = "https://identity.staging.idlrpts.gov.ng/realms/idlrpts";
const STAGING_CLIENT_ID = "idlrpts-mobile";
const STAGING_REDIRECT_URI = "idlrpts://oauth/callback";
const oidc = { issuer: process.env.EXPO_PUBLIC_OIDC_ISSUER || STAGING_ISSUER, clientId: process.env.EXPO_PUBLIC_OIDC_CLIENT_ID || STAGING_CLIENT_ID, redirectUri: process.env.EXPO_PUBLIC_OIDC_REDIRECT_URI || STAGING_REDIRECT_URI };
export default function SignupScreen(){const[busy,setBusy]=useState(false);const start=async()=>{setBusy(true);try{await signInWithPkce(oidc,true);router.replace("/onboarding");}catch(e){Alert.alert("Registration unavailable",e instanceof Error?e.message:"Unable to start registration.");}finally{setBusy(false);}};return <ScreenContainer><View style={s.page}><Text style={s.title}>Create stakeholder access</Text><Text style={s.copy}>Your identity provider creates the account. You will then complete business profile, KYB evidence, and review steps. Account creation does not create land, permit, payment, or trust approval.</Text><Pressable onPress={start} disabled={busy} style={[s.button,busy&&s.disabled]}>{busy?<ActivityIndicator color="#fff"/>:<Text style={s.buttonText}>Start secure registration</Text>}</Pressable><Text style={s.note}>Registration is available only when the enterprise OIDC provider enables self-registration.</Text></View></ScreenContainer>};
const s=StyleSheet.create({page:{flex:1,justifyContent:"center",padding:24,gap:16},title:{fontSize:30,fontWeight:"800",color:"#12263A"},copy:{fontSize:16,lineHeight:24,color:"#475467"},button:{backgroundColor:"#0B6E4F",padding:16,borderRadius:12,alignItems:"center"},disabled:{opacity:.55},buttonText:{color:"white",fontWeight:"700"},note:{fontSize:12,lineHeight:18,color:"#667085",textAlign:"center"}});
