import { useState } from "react";
import { Modal, Pressable, ScrollView, Text, View } from "react-native";
import { trpc } from "@/lib/trpc";

export function RuntimeStatusNotificationCenter() {
  const [open, setOpen] = useState(false);
  const alerts = trpc.integrationSettings.runtimeAlerts.useQuery({ limit: 50 }, { retry: false, refetchInterval: 15_000 });
  const utils = trpc.useUtils(); const acknowledge = trpc.integrationSettings.acknowledgeRuntimeAlert.useMutation({ onSuccess: () => utils.integrationSettings.runtimeAlerts.invalidate() });
  if (alerts.isError) return null;
  const outstanding = alerts.data?.filter((alert) => !alert.acknowledged).length ?? 0;
  return <View style={{ position: "absolute", right: 90, top: 12, zIndex: 30 }}><Pressable accessibilityRole="button" accessibilityLabel="Administrator runtime alerts" onPress={() => setOpen(true)}><View className={`rounded-full border px-3 py-2 shadow-sm ${outstanding ? "border-warning bg-warning/10" : "border-border bg-background"}`}><Text className={`text-xs font-bold ${outstanding ? "text-warning" : "text-foreground"}`}>Runtime{outstanding ? ` · ${outstanding > 9 ? "9+" : outstanding}` : ""}</Text></View></Pressable><Modal visible={open} transparent animationType="fade" onRequestClose={() => setOpen(false)}><Pressable className="flex-1 bg-black/40" onPress={() => setOpen(false)}><Pressable className="absolute right-3 top-14 w-[350px] rounded-2xl border border-border bg-background p-4 shadow-xl" onPress={(event) => event.stopPropagation()}><Text className="text-lg font-bold text-foreground">Runtime health alerts</Text><Text className="mt-1 text-xs leading-4 text-muted">Visible only to administrators. Alert state is derived from authenticated staging probes and is not a substitute for external monitoring operations.</Text><ScrollView className="mt-3" style={{ maxHeight: 400 }}>{alerts.isLoading ? <Text className="py-5 text-center text-sm text-muted">Loading alerts…</Text> : alerts.data?.length ? alerts.data.map((alert) => <View key={alert.eventId} className={`mb-3 rounded-xl border p-3 ${alert.acknowledged ? "border-border bg-surface" : "border-warning bg-background"}`}><Text className={`text-xs font-bold ${alert.acknowledged ? "text-muted" : "text-warning"}`}>{alert.acknowledged ? "ACKNOWLEDGED" : "REVIEW REQUIRED"}</Text><Text className="mt-1 text-xs font-semibold text-foreground">{alert.payload.service ?? "staging service"}</Text><Text className="mt-1 text-xs leading-4 text-muted">{alert.payload.detail ?? "The authenticated staging probe did not succeed."}</Text><Text className="mt-1 text-[11px] text-muted">{new Date(alert.occurredAt).toLocaleString()}</Text>{!alert.acknowledged ? <Pressable onPress={() => void acknowledge.mutateAsync({ alertEventId: alert.eventId })} style={{ opacity: acknowledge.isPending ? 0.5 : 1 }}><View className="mt-3 rounded-lg border border-border p-2"><Text className="text-center text-xs font-semibold text-foreground">Acknowledge</Text></View></Pressable> : null}</View>) : <Text className="py-5 text-center text-sm text-muted">No active runtime-health alerts.</Text>}</ScrollView><Pressable onPress={() => setOpen(false)}><Text className="mt-2 text-center text-xs font-semibold text-primary">Close</Text></Pressable></Pressable></Pressable></Modal></View>;
}
