import { useMemo, useState } from "react";
import { Pressable, Text, View } from "react-native";

type AuditEvent = { eventId: string; type: string; actor: string; occurredAt: string; payload: Record<string, string | string[]> };
type Integrity = { valid: boolean; firstInvalidEventId: string | null; hmacStatus: string; reason: string | null } | undefined;

export function SecurityAuditTimeline({ events, integrity }: { events: AuditEvent[]; integrity: Integrity }) {
  const [invalidOnly, setInvalidOnly] = useState(false);
  const visibleEvents = useMemo(() => invalidOnly && integrity?.firstInvalidEventId ? events.filter((event) => event.eventId === integrity.firstInvalidEventId) : events, [events, integrity?.firstInvalidEventId, invalidOnly]);
  const invalidPresent = Boolean(integrity?.firstInvalidEventId && events.some((event) => event.eventId === integrity.firstInvalidEventId));
  return <View className="rounded-3xl border border-border bg-surface p-5"><View className="flex-row items-center justify-between gap-3"><View><Text className="text-lg font-semibold text-foreground">Integrity timeline</Text><Text className="mt-1 text-xs text-muted">Newest signed events appear first. A broken link is isolated in red.</Text></View>{integrity?.firstInvalidEventId ? <Pressable onPress={() => setInvalidOnly((value) => !value)}><Text className="text-xs font-semibold text-primary">{invalidOnly ? "Show all" : "Isolate invalid"}</Text></Pressable> : null}</View>{integrity?.firstInvalidEventId && !invalidPresent ? <View className="mt-3 rounded-xl border border-error bg-error/10 p-3"><Text className="text-xs text-error">The first invalid record is outside this loaded page: {integrity.firstInvalidEventId}</Text></View> : null}<View className="mt-4 gap-0">{visibleEvents.length ? visibleEvents.map((event, index) => { const invalid = event.eventId === integrity?.firstInvalidEventId; return <View key={event.eventId} className="flex-row gap-3"><View className="items-center"><View className={`h-3 w-3 rounded-full ${invalid ? "bg-error" : "bg-success"}`} />{index < visibleEvents.length - 1 ? <View className={`w-0.5 flex-1 ${invalid ? "bg-error/40" : "bg-border"}`} /> : null}</View><View className={`mb-4 flex-1 rounded-2xl border p-3 ${invalid ? "border-error bg-error/10" : "border-border bg-background"}`}><Text className={`text-xs font-semibold ${invalid ? "text-error" : "text-foreground"}`}>{invalid ? "Integrity break" : event.type.replace(/_/g, " ")}</Text><Text className="mt-1 text-xs text-muted">{event.actor} · {new Date(event.occurredAt).toLocaleString()}</Text><Text className="mt-1 text-[11px] text-muted">Event {event.eventId}</Text></View></View>; }) : <Text className="mt-4 text-sm text-muted">No audit events match this integrity filter.</Text>}</View></View>;
}
