import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ActivityIndicator, Animated, Modal, Pressable, ScrollView, Text, TextInput, View } from "react-native";
import { router } from "expo-router";

import { cancelScheduledStakeholderRetry, getDeadLetterForEditing, getPendingStakeholderSyncItems, retryAllRecoverableStakeholderSyncItems, retryStakeholderSyncItem, updateDeadLetterForRetry, type EditableStakeholderPayload, type PendingStakeholderSyncItem } from "@/lib/stakeholder-sync-queue";
import { describeStakeholderSyncFailure } from "@/lib/stakeholder-sync-error-details";
import { filterAndSortStakeholderSyncItems, getBulkRetryEligibleStakeholderItems, type StakeholderQueueFilter, type StakeholderQueueSort } from "@/lib/stakeholder-sync-view";
import { validateDeadLetterEdit } from "@/lib/stakeholder-sync-validation";
import { describeStakeholderRetrySchedule } from "@/lib/stakeholder-sync-retry";
import { exportAdministrativePublicKeyStakeholderDiagnostics, exportEncryptedStakeholderSyncDiagnostics, exportStakeholderSyncDiagnostics } from "@/lib/stakeholder-sync-diagnostics";
import { confirmEncryptedDiagnosticsExport } from "@/lib/biometric-diagnostic-export";
import { getAdministrativeSupportKeyFingerprint } from "@/lib/stakeholder-support-crypto";
import { createAndDownloadDiagnosticExportReceipt } from "@/lib/stakeholder-export-receipt";
import { shouldShowTechnicalRetryAudit } from "@/lib/stakeholder-sync-audit-visibility";
import { confirmTechnicalQueueViewAuthorization } from "@/lib/technical-queue-view";

const LABELS: Record<PendingStakeholderSyncItem["kind"], string> = { profile: "Stakeholder profile", identity_document: "Identity document", business_document: "Business document" };
const FILTERS: StakeholderQueueFilter[] = ["all", "pending", "failed", "paused", "dead_letter"];

export function StakeholderSyncQueue() {
  const [items, setItems] = useState<PendingStakeholderSyncItem[]>([]); const [loading, setLoading] = useState(true); const [filter, setFilter] = useState<StakeholderQueueFilter>("all"); const [sort, setSort] = useState<StakeholderQueueSort>("newest"); const [retrying, setRetrying] = useState<string | null>(null); const [retryingAll, setRetryingAll] = useState(false); const [exporting, setExporting] = useState(false); const [exportingEncrypted, setExportingEncrypted] = useState(false); const [exportingAdmin, setExportingAdmin] = useState(false); const [supportModal, setSupportModal] = useState(false); const [supportPassphrase, setSupportPassphrase] = useState(""); const [editing, setEditing] = useState<PendingStakeholderSyncItem | null>(null); const [draft, setDraft] = useState<EditableStakeholderPayload | null>(null); const [feedback, setFeedback] = useState<string | null>(null); const [editErrors, setEditErrors] = useState<Record<string, string>>({}); const [toast, setToast] = useState<string | null>(null); const [simplifiedView, setSimplifiedView] = useState(true); const [authorizingTechnical, setAuthorizingTechnical] = useState(false); const [administratorFingerprint, setAdministratorFingerprint] = useState<string | null>(null); const [receiptSummary, setReceiptSummary] = useState<string | null>(null); const receiptScale = useRef(new Animated.Value(0.92)).current; const administratorPublicKey = process.env.EXPO_PUBLIC_SUPPORT_DIAGNOSTICS_X25519_PUBLIC_KEY?.trim() ?? "";
  const refresh = useCallback(async () => { setLoading(true); try { setItems(await getPendingStakeholderSyncItems()); } finally { setLoading(false); } }, []);
  useEffect(() => { void refresh(); }, [refresh]);
  useEffect(() => { if (!administratorPublicKey) { setAdministratorFingerprint(null); return; } void getAdministrativeSupportKeyFingerprint(administratorPublicKey).then(setAdministratorFingerprint).catch(() => setAdministratorFingerprint(null)); }, [administratorPublicKey]);
  useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(null), 4200); return () => clearTimeout(timer); }, [toast]);
  useEffect(() => { if (!receiptSummary) return; const timer = setTimeout(() => setReceiptSummary(null), 6000); return () => clearTimeout(timer); }, [receiptSummary]);
  const visibleItems = useMemo(() => filterAndSortStakeholderSyncItems(items, filter, sort), [filter, items, sort]);
  const openEditor = async (item: PendingStakeholderSyncItem) => { setFeedback(null); setEditErrors({}); try { setDraft(await getDeadLetterForEditing(item.id)); setEditing(item); } catch (error) { setFeedback(error instanceof Error ? error.message : "Could not open this encrypted payload for review."); } };
  const saveEdit = async () => { if (!editing || !draft) return; const errors = validateDeadLetterEdit(draft); if (Object.keys(errors).length) { setEditErrors(errors); return; } try { await updateDeadLetterForRetry(editing.id, draft); setEditing(null); setDraft(null); setEditErrors({}); setFeedback("Edits were re-encrypted with a new idempotency key. Retry when ready."); await refresh(); } catch (error) { setFeedback(error instanceof Error ? error.message : "The changes could not be secured."); } };
  const retry = async (item: PendingStakeholderSyncItem) => { const wasDeadLetter = item.status === "dead_letter"; setRetrying(item.id); setFeedback(null); try { await retryStakeholderSyncItem(item.id); const message = `${item.label} synchronized successfully.`; setFeedback(message); if (wasDeadLetter) setToast("Recovered submission synchronized successfully."); } catch (error) { setFeedback(error instanceof Error ? error.message : "Synchronization failed. The item remains protected in the queue."); } finally { setRetrying(null); await refresh(); } };
  const retryAll = async () => { setRetryingAll(true); setFeedback(null); try { const result = await retryAllRecoverableStakeholderSyncItems(); setFeedback(result.attempted === 0 ? "No failed items are eligible for bulk retry." : `${result.synchronized} of ${result.attempted} failed items synchronized; ${result.failed} remain queued.`); } finally { setRetryingAll(false); await refresh(); } };
  const cancelRetry = async (item: PendingStakeholderSyncItem) => { try { await cancelScheduledStakeholderRetry(item.id); setFeedback(`Automatic retry for ${item.label} was paused. The encrypted item remains on this device.`); await refresh(); } catch (error) { setFeedback(error instanceof Error ? error.message : "The scheduled retry could not be paused."); } };
  const exportDiagnostics = async () => { setExporting(true); setFeedback(null); try { await exportStakeholderSyncDiagnostics(); setFeedback("Queue diagnostics were prepared without document payloads or personal stakeholder fields."); } catch (error) { setFeedback(error instanceof Error ? error.message : "Diagnostics could not be exported on this device."); } finally { setExporting(false); } };
  const openBiometricSupportExport = async () => { const authorization = await confirmEncryptedDiagnosticsExport(); if (!authorization.approved) { setFeedback(authorization.message); return; } setSupportModal(true); };
  const showReceiptSuccess = (summary: string) => { setReceiptSummary(summary); receiptScale.setValue(0.92); Animated.sequence([Animated.timing(receiptScale, { toValue: 1.03, duration: 160, useNativeDriver: true }), Animated.timing(receiptScale, { toValue: 1, duration: 130, useNativeDriver: true })]).start(); };
  const exportEncryptedDiagnostics = async () => { setExportingEncrypted(true); try { const envelope = await exportEncryptedStakeholderSyncDiagnostics(supportPassphrase); setSupportModal(false); setSupportPassphrase(""); try { const receipt = await createAndDownloadDiagnosticExportReceipt(envelope, "passphrase_encrypted"); showReceiptSuccess(`Passphrase-encrypted package exported. Receipt ${receipt.receiptId} confirms digest ${receipt.packageSha256.slice(0, 16)}…`); setFeedback("Encrypted support diagnostics and a signed device receipt were prepared. Share the passphrase only through a separate authorized support channel."); } catch (receiptError) { setFeedback(`Encrypted support diagnostics were prepared, but the receipt could not be shared: ${receiptError instanceof Error ? receiptError.message : "unknown receipt error"}`); } } catch (error) { setFeedback(error instanceof Error ? error.message : "The encrypted support package could not be created."); } finally { setExportingEncrypted(false); } };
  const exportAdministrativeDiagnostics = async () => { const authorization = await confirmEncryptedDiagnosticsExport(); if (!authorization.approved) { setFeedback(authorization.message); return; } setExportingAdmin(true); try { const envelope = await exportAdministrativePublicKeyStakeholderDiagnostics(administratorPublicKey); try { const receipt = await createAndDownloadDiagnosticExportReceipt(envelope, "administrative_public_key"); showReceiptSuccess(`Administrative-key package exported. Receipt ${receipt.receiptId} confirms digest ${receipt.packageSha256.slice(0, 16)}…`); setFeedback("An administrative public-key support package and signed device receipt were prepared after biometric confirmation."); } catch (receiptError) { setFeedback(`The administrative support package was prepared, but the receipt could not be shared: ${receiptError instanceof Error ? receiptError.message : "unknown receipt error"}`); } } catch (error) { setFeedback(error instanceof Error ? error.message : "The administrative support package could not be created."); } finally { setExportingAdmin(false); } };
  const toggleQueueView = async () => { if (!simplifiedView) { setSimplifiedView(true); return; } setAuthorizingTechnical(true); const authorization = await confirmTechnicalQueueViewAuthorization(); setAuthorizingTechnical(false); if (!authorization.approved) { setFeedback(authorization.message); return; } setSimplifiedView(false); setFeedback("Technical queue history is now visible for this session."); };
  const patchProfile = (key: NonNullable<EditableStakeholderPayload["profile"]> extends infer P ? keyof P : never, value: string) => setDraft((current) => current?.profile ? { ...current, profile: { ...current.profile, [key]: value || null } } : current);
  const patchDocument = (key: "type" | "fileName" | "mimeType", value: string) => setDraft((current) => current?.document ? { ...current, document: { ...current.document, [key]: value } } : current);
  return <View className="rounded-3xl border border-border bg-surface p-5"><View className="flex-row items-center justify-between gap-3"><View className="flex-1"><Text className="text-lg font-semibold text-foreground">Offline synchronization queue</Text><Text className="mt-1 text-sm text-muted">Encrypted stakeholder profiles and documents awaiting secure transmission.</Text></View><Text className={`text-xs font-semibold ${items.length ? "text-warning" : "text-success"}`}>{items.length ? `${items.length} queued` : "Clear"}</Text></View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} className="mt-4"><View className="flex-row gap-2">{FILTERS.map((option) => <Pressable key={option} onPress={() => setFilter(option)} style={{ opacity: 1 }}><View className={`rounded-full border px-3 py-2 ${filter === option ? "border-primary bg-primary" : "border-border bg-background"}`}><Text className={`text-xs font-semibold ${filter === option ? "text-white" : "text-foreground"}`}>{option === "all" ? "All" : option.replace("_", " ")}</Text></View></Pressable>)}<Pressable onPress={() => setSort((value) => value === "newest" ? "oldest" : value === "oldest" ? "status" : "newest")}><View className="rounded-full border border-border bg-background px-3 py-2"><Text className="text-xs font-semibold text-foreground">Sort: {sort}</Text></View></Pressable><Pressable disabled={authorizingTechnical} onPress={() => void toggleQueueView()} style={{ opacity: authorizingTechnical ? 0.55 : 1 }}><View className={`rounded-full border px-3 py-2 ${simplifiedView ? "border-primary bg-primary" : "border-border bg-background"}`}><Text className={`text-xs font-semibold ${simplifiedView ? "text-white" : "text-foreground"}`}>{authorizingTechnical ? "Authorizing…" : simplifiedView ? "Unlock technical view" : "Standard view"}</Text></View></Pressable></View></ScrollView>
    {loading ? <View className="mt-4 flex-row items-center gap-2"><ActivityIndicator size="small" /><Text className="text-sm text-muted">Checking this device…</Text></View> : visibleItems.length === 0 ? <Text className="mt-4 text-sm leading-5 text-muted">No {filter === "all" ? "stakeholder profile or document submissions" : filter.replace("_", " ")} items match this view.</Text> : <View className="mt-4 gap-3">{visibleItems.map((item) => <View key={item.id} className={`rounded-2xl border p-4 ${item.status === "dead_letter" ? "border-error bg-background" : item.status === "paused" ? "border-warning bg-background" : "border-border bg-background"}`}><View className="flex-row justify-between gap-3"><View className="flex-1"><Text className="font-semibold text-foreground">{item.label || LABELS[item.kind]}</Text><Text className="mt-1 text-sm text-muted">{LABELS[item.kind]} · {item.status.replace(/_/g, " ")} · attempt {item.retryCount + 1}</Text><Text className="mt-1 text-xs text-muted">Queued {new Date(item.queuedAt).toLocaleString()}</Text></View><Text className={`text-xs font-semibold ${item.status === "dead_letter" ? "text-error" : item.status === "failed" || item.status === "paused" ? "text-warning" : "text-muted"}`}>{item.status === "dead_letter" ? "Inspection required" : item.status === "paused" ? "Paused" : item.status === "failed" ? "Retry available" : "Waiting"}</Text></View>{item.status === "failed" || item.status === "dead_letter" ? <Text className="mt-3 text-xs leading-4 text-error">{describeStakeholderSyncFailure(item)}</Text> : null}{describeStakeholderRetrySchedule(item) ? <Text className="mt-2 text-xs font-semibold text-warning">{describeStakeholderRetrySchedule(item)}</Text> : null}{shouldShowTechnicalRetryAudit(simplifiedView, item) ? <View className="mt-3 rounded-xl border border-border bg-surface p-3"><Text className="text-xs font-semibold text-foreground">Retry activity</Text>{item.retryAudit?.slice().reverse().map((event, index) => <Text key={`${event.at}-${index}`} className="mt-1 text-xs leading-4 text-muted">{new Date(event.at).toLocaleString()} · {event.action.replace(/_/g, " ")} — {event.detail}</Text>)}</View> : null}<View className="mt-3 flex-row flex-wrap gap-4">{item.status === "dead_letter" ? <Pressable onPress={() => void openEditor(item)}><Text className="font-semibold text-primary">Review and edit</Text></Pressable> : null}{item.status === "failed" && item.nextRetryAt ? <Pressable onPress={() => void cancelRetry(item)}><Text className="font-semibold text-warning">Cancel scheduled retry</Text></Pressable> : null}<Pressable disabled={retrying === item.id || item.status === "retrying"} onPress={() => void retry(item)} style={{ opacity: retrying === item.id || item.status === "retrying" ? 0.55 : 1 }}><Text className="font-semibold text-primary">{retrying === item.id ? "Synchronizing…" : item.status === "paused" ? "Resume with manual retry" : "Retry synchronization"}</Text></Pressable></View></View>)}</View>}
    {feedback ? <Text className="mt-4 text-sm leading-5 text-muted">{feedback}</Text> : null}{administratorFingerprint ? <Text className="mt-3 text-xs font-semibold text-muted">Administrative encryption key fingerprint: {administratorFingerprint}</Text> : <Text className="mt-3 text-xs text-muted">Administrative public-key encryption is unavailable until a verified key is configured.</Text>}<View className="mt-4 flex-row flex-wrap gap-4"><Pressable onPress={() => void retryAll()} disabled={retryingAll || getBulkRetryEligibleStakeholderItems(items).length === 0} style={{ opacity: retryingAll || getBulkRetryEligibleStakeholderItems(items).length === 0 ? 0.55 : 1 }}><Text className="font-semibold text-primary">{retryingAll ? "Retrying failed items…" : "Retry all failed"}</Text></Pressable><Pressable onPress={() => void exportDiagnostics()} disabled={exporting} style={{ opacity: exporting ? 0.55 : 1 }}><Text className="font-semibold text-primary">{exporting ? "Preparing diagnostics…" : "Share diagnostics"}</Text></Pressable><Pressable onPress={() => void openBiometricSupportExport()}><Text className="font-semibold text-primary">Encrypted support package</Text></Pressable><Pressable onPress={() => void exportAdministrativeDiagnostics()} disabled={exportingAdmin || !administratorPublicKey} style={{ opacity: exportingAdmin || !administratorPublicKey ? 0.55 : 1 }}><Text className="font-semibold text-primary">{exportingAdmin ? "Encrypting…" : administratorPublicKey ? "Admin-key package" : "Admin key unavailable"}</Text></Pressable><Pressable onPress={() => router.push("/diagnostic-receipt-verification" as never)}><Text className="font-semibold text-primary">Verify a receipt</Text></Pressable><Pressable onPress={() => void refresh()} disabled={loading} style={{ opacity: loading ? 0.6 : 1 }}><Text className="font-semibold text-primary">Refresh queue status</Text></Pressable></View>
    {toast ? <View className="absolute bottom-4 left-4 right-4 rounded-2xl border border-success bg-background p-4 shadow-lg"><Text className="font-semibold text-success">Synchronization complete</Text><Text className="mt-1 text-sm text-foreground">{toast}</Text></View> : null}{receiptSummary ? <Animated.View style={{ transform: [{ scale: receiptScale }] }} className="absolute bottom-4 left-4 right-4 rounded-2xl border border-success bg-background p-4 shadow-lg"><Text className="font-semibold text-success">Diagnostic export complete</Text><Text className="mt-1 text-sm leading-5 text-foreground">{receiptSummary}</Text></Animated.View> : null}
    <Modal visible={supportModal} transparent animationType="slide" onRequestClose={() => { setSupportModal(false); setSupportPassphrase(""); }}><View className="flex-1 justify-end bg-black/50"><View className="rounded-t-3xl bg-background p-6"><Text className="text-xl font-bold text-foreground">Encrypted support package</Text><Text className="mt-2 text-sm leading-5 text-muted">Enter the 12-character or longer passphrase issued in your authorized support case. Share the exported package and passphrase through separate approved channels.</Text><TextInput value={supportPassphrase} onChangeText={setSupportPassphrase} secureTextEntry autoCapitalize="none" className="mt-4 rounded-xl border border-border bg-surface px-3 py-3 text-foreground" placeholder="Authorized support passphrase" placeholderTextColor="#667085" /><View className="mt-5 flex-row gap-3"><Pressable onPress={() => { setSupportModal(false); setSupportPassphrase(""); }} style={{ flex: 1 }}><View className="rounded-2xl border border-border p-4"><Text className="text-center font-semibold text-foreground">Cancel</Text></View></Pressable><Pressable onPress={() => void exportEncryptedDiagnostics()} disabled={exportingEncrypted || supportPassphrase.trim().length < 12} style={{ flex: 1, opacity: exportingEncrypted || supportPassphrase.trim().length < 12 ? 0.55 : 1 }}><View className="rounded-2xl bg-primary p-4"><Text className="text-center font-semibold text-white">{exportingEncrypted ? "Encrypting…" : "Create package"}</Text></View></Pressable></View></View></View></Modal>
    <Modal visible={Boolean(editing && draft)} transparent animationType="slide" onRequestClose={() => { setEditing(null); setDraft(null); setEditErrors({}); }}><View className="flex-1 justify-end bg-black/50"><View className="max-h-[85%] rounded-t-3xl bg-background p-6"><Text className="text-xl font-bold text-foreground">Correct quarantined submission</Text><Text className="mt-2 text-sm leading-5 text-muted">Only editable metadata is shown. The original encrypted document content is retained; saving creates a new encryption envelope and idempotency key.</Text><ScrollView className="mt-4">{draft?.profile ? <View className="gap-3">{(["companyName", "cacNumber", "tinNumber", "businessEmail", "businessPhone", "businessAddress", "contactPerson"] as const).map((field) => <View key={field}><Text className="mb-1 text-xs font-semibold text-muted">{field.replace(/([A-Z])/g, " $1")}</Text><TextInput value={draft.profile?.[field] ?? ""} onChangeText={(value) => patchProfile(field, value)} className="rounded-xl border border-border bg-surface px-3 py-3 text-foreground" autoCapitalize="none" />{editErrors[field] ? <Text className="mt-1 text-xs text-error">{editErrors[field]}</Text> : null}</View>)}</View> : draft?.document ? <View className="gap-3">{(["type", "fileName", "mimeType"] as const).map((field) => <View key={field}><Text className="mb-1 text-xs font-semibold text-muted">{field.replace(/([A-Z])/g, " $1")}</Text><TextInput value={draft.document?.[field] ?? ""} onChangeText={(value) => patchDocument(field, value)} className="rounded-xl border border-border bg-surface px-3 py-3 text-foreground" autoCapitalize="none" />{editErrors[field] ? <Text className="mt-1 text-xs text-error">{editErrors[field]}</Text> : null}</View>)}</View> : null}</ScrollView><View className="mt-5 flex-row gap-3"><Pressable onPress={() => { setEditing(null); setDraft(null); setEditErrors({}); }} style={{ flex: 1 }}><View className="rounded-2xl border border-border p-4"><Text className="text-center font-semibold text-foreground">Cancel</Text></View></Pressable><Pressable onPress={() => void saveEdit()} style={{ flex: 1 }}><View className="rounded-2xl bg-primary p-4"><Text className="text-center font-semibold text-white">Secure edits</Text></View></Pressable></View></View></View></Modal>
  </View>;
}
