import { useState } from "react";
import Svg, { Circle, Line, Polyline } from "react-native-svg";
import { Pressable, Text, View } from "react-native";

import type { WafTrendPoint } from "@/server/securityTelemetry";

export function WafBlockTrendChart({ points }: { points: WafTrendPoint[] }) {
  const [selectedIndex, setSelectedIndex] = useState<number | null>(null);
  if (!points.length) return <View className="mt-4 rounded-2xl border border-dashed border-border bg-background p-4"><Text className="text-sm text-muted">No verified 24-hour WAF history is available.</Text></View>;
  const width = 320; const height = 120; const max = Math.max(1, ...points.map((point) => point.blockedRequests));
  const coordinates = points.map((point, index) => `${(index / Math.max(1, points.length - 1)) * width},${height - (point.blockedRequests / max) * (height - 10)}`).join(" ");
  const selected = selectedIndex === null ? null : points[selectedIndex];
  return <View className="mt-4 rounded-2xl border border-border bg-background p-3"><Svg width="100%" height={height} viewBox={`0 0 ${width} ${height}`}><Line x1="0" y1={height} x2={width} y2={height} stroke="#D0D5DD" strokeWidth="1" /><Polyline points={coordinates} fill="none" stroke="#D92D20" strokeWidth="3" />{points.map((point, index) => <Circle key={`${point.timestamp}-${index}`} cx={(index / Math.max(1, points.length - 1)) * width} cy={height - (point.blockedRequests / max) * (height - 10)} r={selectedIndex === index ? 6 : 4} fill={selectedIndex === index ? "#B42318" : "#D92D20"} onPress={() => setSelectedIndex(index)} />)}</Svg><View className="mt-2 flex-row justify-between"><Text className="text-xs text-muted">{new Date(points[0]!.timestamp).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</Text><Text className="text-xs text-muted">{new Date(points.at(-1)!.timestamp).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</Text></View>{selected ? <View className="mt-3 rounded-xl border border-border bg-surface p-3"><View className="flex-row items-center justify-between"><Text className="text-xs font-semibold text-foreground">{new Date(selected.timestamp).toLocaleString()}</Text><Pressable onPress={() => setSelectedIndex(null)}><Text className="text-xs font-semibold text-primary">Close</Text></Pressable></View><Text className="mt-1 text-sm font-semibold text-error">{selected.blockedRequests} blocked requests</Text><Text className="mt-2 text-xs text-muted">Threat types: {selected.threatTypes.length ? selected.threatTypes.join(", ") : "Not supplied by telemetry"}</Text><Text className="mt-1 text-xs text-muted">Sources: {selected.sourceAddresses.length ? selected.sourceAddresses.join(", ") : "Not supplied by telemetry"}</Text><Text className="mt-2 text-[11px] text-muted">Source addresses are redacted before display.</Text></View> : <Text className="mt-3 text-xs text-muted">Tap a point to view verified interval detail.</Text>}</View>;
}
