import type { Express, Request } from "express";
import { exportJWK, generateKeyPair, jwtVerify, SignJWT } from "jose";

const enabled = () => process.env.NODE_ENV !== "production" && process.env.ENABLE_DEVELOPMENT_PROVIDER_EMULATORS === "true";
const keyPair = generateKeyPair("RS256");
const keyId = "idlr-pts-development-emulator";

function baseUrl(req: Request) {
  return `${req.protocol}://${req.get("host")}/api/dev-emulators/keycloak`;
}

async function requireDevelopmentToken(req: Request) {
  const authorization = req.header("authorization");
  const token = authorization?.startsWith("Bearer ") ? authorization.slice("Bearer ".length) : null;
  if (!token) return { ok: false as const, reason: "A test-only Keycloak emulator bearer token is required." };
  try {
    const result = await jwtVerify(token, (await keyPair).publicKey, { issuer: baseUrl(req) });
    if (result.payload.emulator !== true || result.payload.verified !== false) return { ok: false as const, reason: "Only explicitly non-verifying emulator tokens may access this endpoint." };
    return { ok: true as const };
  } catch {
    return { ok: false as const, reason: "The supplied development emulator token is invalid or expired." };
  }
}

export function registerDevelopmentProviderEmulators(app: Express) {
  app.get("/api/dev-emulators/status", (_req, res) => {
    res.json({ enabled: enabled(), environment: process.env.NODE_ENV ?? "development", mode: "test_only", liveVerification: false, warning: "Development provider emulators are never live services and must not be used for production verification." });
  });

  app.get("/api/dev-emulators/keycloak/.well-known/openid-configuration", (req, res) => {
    if (!enabled()) return res.status(404).json({ error: "development_emulator_disabled" });
    const issuer = baseUrl(req);
    return res.json({ issuer, jwks_uri: `${issuer}/certs`, token_endpoint: `${issuer}/token`, response_types_supported: ["token"], grant_types_supported: ["client_credentials"], emulator: true, productionUseProhibited: true });
  });

  app.get("/api/dev-emulators/keycloak/certs", async (_req, res) => {
    if (!enabled()) return res.status(404).json({ error: "development_emulator_disabled" });
    const publicKey = await exportJWK((await keyPair).publicKey);
    return res.json({ keys: [{ ...publicKey, kid: keyId, use: "sig", alg: "RS256" }], emulator: true, productionUseProhibited: true });
  });

  app.post("/api/dev-emulators/keycloak/token", async (req, res) => {
    if (!enabled()) return res.status(404).json({ error: "development_emulator_disabled" });
    const issuer = baseUrl(req);
    const audience = typeof req.body?.audience === "string" ? req.body.audience : "idlr-pts-clients";
    const role = typeof req.body?.agency_role === "string" ? req.body.agency_role : "planning_supervisor";
    const token = await new SignJWT({
      email: "development-emulator@idlr-pts.local",
      name: "Development Emulator Operator",
      agency_id: "development-emulator-agency",
      agency_roles: [role],
      emulator: true,
      verified: false,
      warning: "TEST-ONLY TOKEN. NOT A LIVE KEYCLOAK IDENTITY.",
    })
      .setProtectedHeader({ alg: "RS256", kid: keyId })
      .setSubject("development-emulator-user")
      .setIssuer(issuer)
      .setAudience(audience)
      .setIssuedAt()
      .setExpirationTime("5m")
      .sign((await keyPair).privateKey);
    return res.json({ access_token: token, token_type: "Bearer", expires_in: 300, emulator: true, productionUseProhibited: true, warning: "TEST-ONLY TOKEN. It must never authorize a production workflow." });
  });

  app.post("/api/dev-emulators/docling/v1/convert/source", async (req, res) => {
    if (!enabled()) return res.status(404).json({ error: "development_emulator_disabled" });
    const authorization = await requireDevelopmentToken(req);
    if (!authorization.ok) return res.status(401).json({ error: "development_emulator_auth_required", message: authorization.reason, emulator: true, productionUseProhibited: true });
    const files = Array.isArray(req.body?.file_sources) ? req.body.file_sources : [];
    const documents = files.map((file: { filename?: unknown }) => ({
      markdown: `# TEST-ONLY DOC LING EMULATOR\n\nThis conversion was generated by a development emulator for ${typeof file.filename === "string" ? file.filename : "unnamed file"}. It does not attest to document authenticity, extraction accuracy, ownership, identity, or registry status.`,
      text: "TEST-ONLY EMULATOR OUTPUT — no live document intelligence result is available.",
      emulator: true,
      verified: false,
    }));
    return res.json({ documents, emulator: true, productionUseProhibited: true, warning: "TEST-ONLY DOCUMENT CONVERSION. NOT A DOCLING PRODUCTION RESULT." });
  });

  app.post("/api/dev-emulators/bridges/:provider", async (req, res) => {
    if (!enabled()) return res.status(404).json({ error: "development_emulator_disabled" });
    const authorization = await requireDevelopmentToken(req);
    if (!authorization.ok) return res.status(401).json({ error: "development_emulator_auth_required", message: authorization.reason, emulator: true, productionUseProhibited: true });
    const provider = req.params.provider;
    if (!["nimc", "cac", "state-registry"].includes(provider)) return res.status(404).json({ error: "unsupported_development_bridge", emulator: true });
    return res.json({ status: "requires_review", providerReference: `development-emulator-${provider}`, reason: "TEST-ONLY BRIDGE RESPONSE. It does not verify identity, company registration, title ownership, or registry authority.", attributes: { emulator: true, verified: false }, emulator: true, productionUseProhibited: true });
  });
}
