import type { Express, Request } from "express";
import { exportJWK, generateKeyPair, SignJWT } from "jose";

const enabled = () => process.env.NODE_ENV !== "production" && process.env.ENABLE_DEVELOPMENT_PROVIDER_EMULATORS === "true";
const keyPair = generateKeyPair("RS256");
const keyId = "idlr-pts-development-emulator";

function baseUrl(req: Request) {
  return `${req.protocol}://${req.get("host")}/api/dev-emulators/keycloak`;
}

export function registerDevelopmentProviderEmulators(app: Express) {
  app.get("/api/dev-emulators/status", (_req, res) => {
    res.json({ enabled: enabled(), environment: process.env.NODE_ENV ?? "development", mode: "test_only", liveVerification: false, warning: "Development provider emulators are never live services and must not be used for production verification." });
  });

  app.get("/api/dev-emulators/keycloak/.well-known/openid-configuration", (req, res) => {
    if (!enabled()) return res.status(404).json({ error: "development_emulator_disabled" });
    const issuer = baseUrl(req);
    return res.json({ issuer, jwks_uri: `${issuer}/certs`, token_endpoint: `${issuer}/token`, response_types_supported: ["token"], grant_types_supported: ["client_credentials"], emulator: true, productionUseProhibited: true });
  });

  app.get("/api/dev-emulators/keycloak/certs", async (_req, res) => {
    if (!enabled()) return res.status(404).json({ error: "development_emulator_disabled" });
    const publicKey = await exportJWK((await keyPair).publicKey);
    return res.json({ keys: [{ ...publicKey, kid: keyId, use: "sig", alg: "RS256" }], emulator: true, productionUseProhibited: true });
  });

  app.post("/api/dev-emulators/keycloak/token", async (req, res) => {
    if (!enabled()) return res.status(404).json({ error: "development_emulator_disabled" });
    const issuer = baseUrl(req);
    const audience = typeof req.body?.audience === "string" ? req.body.audience : "idlr-pts-clients";
    const role = typeof req.body?.agency_role === "string" ? req.body.agency_role : "planning_supervisor";
    const token = await new SignJWT({
      email: "development-emulator@idlr-pts.local",
      name: "Development Emulator Operator",
      agency_id: "development-emulator-agency",
      agency_roles: [role],
      emulator: true,
      verified: false,
      warning: "TEST-ONLY TOKEN. NOT A LIVE KEYCLOAK IDENTITY.",
    })
      .setProtectedHeader({ alg: "RS256", kid: keyId })
      .setSubject("development-emulator-user")
      .setIssuer(issuer)
      .setAudience(audience)
      .setIssuedAt()
      .setExpirationTime("5m")
      .sign((await keyPair).privateKey);
    return res.json({ access_token: token, token_type: "Bearer", expires_in: 300, emulator: true, productionUseProhibited: true, warning: "TEST-ONLY TOKEN. It must never authorize a production workflow." });
  });

  app.post("/api/dev-emulators/docling/v1/convert/source", (req, res) => {
    if (!enabled()) return res.status(404).json({ error: "development_emulator_disabled" });
    const files = Array.isArray(req.body?.file_sources) ? req.body.file_sources : [];
    const documents = files.map((file: { filename?: unknown }) => ({
      markdown: `# TEST-ONLY DOC LING EMULATOR\n\nThis conversion was generated by a development emulator for ${typeof file.filename === "string" ? file.filename : "unnamed file"}. It does not attest to document authenticity, extraction accuracy, ownership, identity, or registry status.`,
      text: "TEST-ONLY EMULATOR OUTPUT — no live document intelligence result is available.",
      emulator: true,
      verified: false,
    }));
    return res.json({ documents, emulator: true, productionUseProhibited: true, warning: "TEST-ONLY DOCUMENT CONVERSION. NOT A DOCLING PRODUCTION RESULT." });
  });
}
