import { desc, eq } from "drizzle-orm";
import { diagnosticAttestationReceipts, type DiagnosticAttestationReceipt } from "../drizzle/schema";
import type { ServerDiagnosticExportReceipt } from "../lib/stakeholder-server-attestation-crypto";
import { getDb } from "./db";

function statusOf(record: DiagnosticAttestationReceipt) { return record.revokedAt ? "revoked" as const : "active" as const; }
function serialize(record: DiagnosticAttestationReceipt) { return { receiptId: record.receiptId, packageType: record.packageType, packageSha256: record.packageSha256, attestedForSubject: record.attestedForSubject, signerKeyId: record.signerKeyId, signerFingerprint: record.signerFingerprint, createdAt: record.createdAt.toISOString(), status: statusOf(record), revokedAt: record.revokedAt?.toISOString() ?? null, revokedBy: record.revokedBy, revocationReason: record.revocationReason }; }
export async function recordDiagnosticAttestation(receipt: ServerDiagnosticExportReceipt) { const db = await getDb(); if (!db) throw new Error("Organization receipt attestation is unavailable because durable receipt storage is not connected."); await db.insert(diagnosticAttestationReceipts).values({ receiptId: receipt.receiptId, packageType: receipt.packageType, packageSha256: receipt.packageSha256, attestedForSubject: receipt.attestedForSubject, signerKeyId: receipt.signer.keyId, signerFingerprint: receipt.signer.fingerprint, receiptJson: JSON.stringify(receipt) }); return receipt; }
export async function listDiagnosticAttestations(limit = 100) { const db = await getDb(); if (!db) throw new Error("Receipt administration is unavailable because durable receipt storage is not connected."); return (await db.select().from(diagnosticAttestationReceipts).orderBy(desc(diagnosticAttestationReceipts.createdAt)).limit(limit)).map(serialize); }
export async function getDiagnosticAttestationStatusByReceiptId(receiptId: string) { const db = await getDb(); if (!db) throw new Error("Organization receipt status is unavailable because durable receipt storage is not connected."); const [record] = await db.select().from(diagnosticAttestationReceipts).where(eq(diagnosticAttestationReceipts.receiptId, receiptId)).limit(1); return record ? { found: true as const, status: statusOf(record), revokedAt: record.revokedAt?.toISOString() ?? null, revocationReason: record.revocationReason } : { found: false as const, status: null, revokedAt: null, revocationReason: null }; }
export async function revokeDiagnosticAttestation(input: { receiptId: string; actorOpenId: string; reason: string }) { const db = await getDb(); if (!db) throw new Error("Receipt administration is unavailable because durable receipt storage is not connected."); const [record] = await db.select().from(diagnosticAttestationReceipts).where(eq(diagnosticAttestationReceipts.receiptId, input.receiptId)).limit(1); if (!record) throw new Error("The organization receipt was not found."); if (record.revokedAt) throw new Error("This organization receipt has already been revoked."); const revokedAt = new Date(); await db.update(diagnosticAttestationReceipts).set({ revokedAt, revokedBy: input.actorOpenId, revocationReason: input.reason }).where(eq(diagnosticAttestationReceipts.receiptId, input.receiptId)); return serialize({ ...record, revokedAt, revokedBy: input.actorOpenId, revocationReason: input.reason }); }
