import PDFDocument from "pdfkit";

export interface RopaRecord {
  id: number;
  activity_name: string;
  processing_purpose?: string;
  lawful_basis?: string;
  data_categories?: string;
  data_subject_categories?: string;
  recipients?: string;
  retention_period?: string;
  security_measures?: string;
  cross_border_transfer?: boolean;
  dpia_required?: boolean;
  ropa_status?: string;
  created_at?: string | Date;
  org_name?: string;
}

export interface RopaPdfData {
  organizationName: string;
  generatedAt: string;
  records: RopaRecord[];
}

/**
 * Generate NDPA-compliant ROPA Register PDF.
 * Returns a Buffer containing the PDF bytes.
 */
export function generateRopaPdf(data: RopaPdfData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    const doc = new PDFDocument({ size: "A4", margin: 50 });
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    // ── Cover header ──────────────────────────────────────────────────────────
    doc.fontSize(18).font("Helvetica-Bold")
      .text("Record of Processing Activities (ROPA)", { align: "center" });
    doc.moveDown(0.4);
    doc.fontSize(12).font("Helvetica")
      .text(`Organisation: ${data.organizationName}`, { align: "center" });
    doc.fontSize(10).fillColor("#555")
      .text(`Generated: ${new Date(data.generatedAt).toLocaleString("en-NG")}`, { align: "center" });
    doc.fontSize(9).fillColor("#777")
      .text("Prepared in compliance with NDPA 2023, Section 44 — Records of Processing Activities", { align: "center" });
    doc.moveDown(1);
    doc.fillColor("#000");

    // ── Summary box ───────────────────────────────────────────────────────────
    doc.rect(50, doc.y, 495, 40).fillAndStroke("#f0f4ff", "#c0c8e0");
    const summaryY = doc.y - 35;
    doc.fillColor("#333").fontSize(10).font("Helvetica-Bold")
      .text(`Total Processing Activities: ${data.records.length}`, 60, summaryY + 8);
    const active = data.records.filter((r) => r.ropa_status === "active").length;
    doc.fontSize(9).font("Helvetica")
      .text(`Active: ${active}   |   Inactive: ${data.records.length - active}`, 60, summaryY + 22);
    doc.moveDown(2);
    doc.fillColor("#000");

    // ── Records ───────────────────────────────────────────────────────────────
    data.records.forEach((rec, idx) => {
      // Page break check
      if (doc.y > 680) doc.addPage();

      // Activity header
      doc.fontSize(11).font("Helvetica-Bold").fillColor("#1a3a6b")
        .text(`${idx + 1}. ${rec.activity_name}`, { underline: false });
      doc.moveDown(0.2);
      doc.fillColor("#000");

      const rows: [string, string][] = [
        ["Processing Purpose", rec.processing_purpose ?? "—"],
        ["Lawful Basis", rec.lawful_basis ?? "—"],
        ["Data Categories", rec.data_categories ?? "—"],
        ["Data Subject Categories", rec.data_subject_categories ?? "—"],
        ["Recipients / Processors", rec.recipients ?? "—"],
        ["Retention Period", rec.retention_period ?? "—"],
        ["Security Measures", rec.security_measures ?? "—"],
        ["Cross-Border Transfer", rec.cross_border_transfer ? "Yes" : "No"],
        ["DPIA Required", rec.dpia_required ? "Yes" : "No"],
        ["Status", rec.ropa_status ?? "active"],
      ];

      rows.forEach(([label, value]) => {
        if (doc.y > 700) doc.addPage();
        const startY = doc.y;
        doc.fontSize(8).font("Helvetica-Bold").fillColor("#444")
          .text(label + ":", 60, startY, { width: 140, continued: false });
        doc.fontSize(8).font("Helvetica").fillColor("#111")
          .text(value, 205, startY, { width: 340 });
        doc.moveDown(0.15);
      });

      // Separator
      doc.moveDown(0.4);
      doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor("#ddd").stroke();
      doc.moveDown(0.6);
      doc.fillColor("#000");
    });

    // ── Footer ────────────────────────────────────────────────────────────────
    if (doc.y > 700) doc.addPage();
    doc.moveDown(1);
    doc.fontSize(8).fillColor("#888")
      .text("This document is generated by the National Data Sovereignty Enforcement Platform (NDSEP).", { align: "center" });
    doc.text("For official use only. Retain for a minimum of 6 years per NDPA 2023.", { align: "center" });

    doc.end();
  });
}
