export type EncryptedSupportPackage = { schema: "idlr-pts.encrypted-support-diagnostics.v1"; algorithm: "AES-256-GCM"; kdf: { algorithm: "PBKDF2-HMAC-SHA-256"; iterations: number; salt: string }; nonce: string; ciphertext: string; note: string };
export type AdministrativePublicKeySupportPackage = { schema: "idlr-pts.admin-public-key-support-diagnostics.v1"; algorithm: "X25519-HKDF-SHA-256-AES-256-GCM"; administrativeKeyFingerprint: string; ephemeralPublicKey: string; salt: string; nonce: string; ciphertext: string; note: string };

async function dependencies() { const [{ gcm }, { bytesToHex, hexToBytes, utf8ToBytes, bytesToUtf8 }, { pbkdf2 }, { sha256 }] = await Promise.all([import("@noble/ciphers/aes.js"), import("@noble/ciphers/utils.js"), import("@noble/hashes/pbkdf2"), import("@noble/hashes/sha256")]); return { gcm, bytesToHex, hexToBytes, utf8ToBytes, bytesToUtf8, pbkdf2, sha256 }; }
export async function encryptAuthorizedSupportDiagnostics(plainText: string, passphrase: string, randomBytes: (length: number) => Uint8Array): Promise<EncryptedSupportPackage> {
  if (passphrase.trim().length < 12) throw new Error("Use the 12-character or longer passphrase issued through your authorized support case.");
  const { gcm, bytesToHex, utf8ToBytes, pbkdf2, sha256 } = await dependencies(); const salt = randomBytes(16); const nonce = randomBytes(12); const derivedKey = pbkdf2(sha256, utf8ToBytes(passphrase), salt, { c: 310_000, dkLen: 32 }); const ciphertext = gcm(derivedKey, nonce).encrypt(utf8ToBytes(plainText));
  return { schema: "idlr-pts.encrypted-support-diagnostics.v1", algorithm: "AES-256-GCM", kdf: { algorithm: "PBKDF2-HMAC-SHA-256", iterations: 310_000, salt: bytesToHex(salt) }, nonce: bytesToHex(nonce), ciphertext: bytesToHex(ciphertext), note: "Share this package only through an authorized support case. Provide the passphrase through a separate approved channel." };
}
export async function decryptAuthorizedSupportDiagnostics(pkg: EncryptedSupportPackage, passphrase: string) { const { gcm, hexToBytes, bytesToUtf8, utf8ToBytes, pbkdf2, sha256 } = await dependencies(); if (pkg.algorithm !== "AES-256-GCM" || pkg.kdf.algorithm !== "PBKDF2-HMAC-SHA-256") throw new Error("Unsupported authorized support package format."); const key = pbkdf2(sha256, utf8ToBytes(passphrase), hexToBytes(pkg.kdf.salt), { c: pkg.kdf.iterations, dkLen: 32 }); return bytesToUtf8(gcm(key, hexToBytes(pkg.nonce)).decrypt(hexToBytes(pkg.ciphertext))); }
export async function encryptForAdministrativeSupport(plainText: string, administratorPublicKeyHex: string, randomBytes: (length: number) => Uint8Array): Promise<AdministrativePublicKeySupportPackage> { const [{ x25519 }, { hkdf }, base] = await Promise.all([import("@noble/curves/ed25519"), import("@noble/hashes/hkdf"), dependencies()]); const administratorPublicKey = base.hexToBytes(administratorPublicKeyHex); if (administratorPublicKey.length !== 32) throw new Error("The configured administrative support public key is invalid."); const ephemeralPrivateKey = randomBytes(32); const ephemeralPublicKey = x25519.getPublicKey(ephemeralPrivateKey); const salt = randomBytes(32); const nonce = randomBytes(12); const sharedSecret = x25519.getSharedSecret(ephemeralPrivateKey, administratorPublicKey); const key = hkdf(base.sha256, sharedSecret, salt, base.utf8ToBytes("idlr-pts/support-diagnostics/v1"), 32); const ciphertext = base.gcm(key, nonce).encrypt(base.utf8ToBytes(plainText)); return { schema: "idlr-pts.admin-public-key-support-diagnostics.v1", algorithm: "X25519-HKDF-SHA-256-AES-256-GCM", administrativeKeyFingerprint: base.bytesToHex(base.sha256(administratorPublicKey)).slice(0, 24), ephemeralPublicKey: base.bytesToHex(ephemeralPublicKey), salt: base.bytesToHex(salt), nonce: base.bytesToHex(nonce), ciphertext: base.bytesToHex(ciphertext), note: "Encrypted for the configured administrative support public key. Share only through an authorized support case." }; }
export async function decryptAdministrativeSupportPackage(pkg: AdministrativePublicKeySupportPackage, administratorPrivateKeyHex: string) { const [{ x25519 }, { hkdf }, base] = await Promise.all([import("@noble/curves/ed25519"), import("@noble/hashes/hkdf"), dependencies()]); if (pkg.algorithm !== "X25519-HKDF-SHA-256-AES-256-GCM") throw new Error("Unsupported administrative support package format."); const privateKey = base.hexToBytes(administratorPrivateKeyHex); const sharedSecret = x25519.getSharedSecret(privateKey, base.hexToBytes(pkg.ephemeralPublicKey)); const key = hkdf(base.sha256, sharedSecret, base.hexToBytes(pkg.salt), base.utf8ToBytes("idlr-pts/support-diagnostics/v1"), 32); return base.bytesToUtf8(base.gcm(key, base.hexToBytes(pkg.nonce)).decrypt(base.hexToBytes(pkg.ciphertext))); }
export async function getAdministrativeSupportKeyFingerprint(administratorPublicKeyHex: string) { const { hexToBytes, bytesToHex, sha256 } = await dependencies(); let publicKey: Uint8Array; try { publicKey = hexToBytes(administratorPublicKeyHex); } catch { throw new Error("The configured administrative support public key is invalid."); } if (publicKey.length !== 32) throw new Error("The configured administrative support public key is invalid."); const hex = bytesToHex(sha256(publicKey)); return hex.match(/.{1,4}/g)?.slice(0, 6).join(":") ?? hex; }
