export type EncryptedSupportPackage = { schema: "idlr-pts.encrypted-support-diagnostics.v1"; algorithm: "AES-256-GCM"; kdf: { algorithm: "PBKDF2-HMAC-SHA-256"; iterations: number; salt: string }; nonce: string; ciphertext: string; note: string };

async function dependencies() { const [{ gcm }, { bytesToHex, hexToBytes, utf8ToBytes, bytesToUtf8 }, { pbkdf2 }, { sha256 }] = await Promise.all([import("@noble/ciphers/aes.js"), import("@noble/ciphers/utils.js"), import("@noble/hashes/pbkdf2"), import("@noble/hashes/sha256")]); return { gcm, bytesToHex, hexToBytes, utf8ToBytes, bytesToUtf8, pbkdf2, sha256 }; }
export async function encryptAuthorizedSupportDiagnostics(plainText: string, passphrase: string, randomBytes: (length: number) => Uint8Array): Promise<EncryptedSupportPackage> {
  if (passphrase.trim().length < 12) throw new Error("Use the 12-character or longer passphrase issued through your authorized support case.");
  const { gcm, bytesToHex, utf8ToBytes, pbkdf2, sha256 } = await dependencies(); const salt = randomBytes(16); const nonce = randomBytes(12); const derivedKey = pbkdf2(sha256, utf8ToBytes(passphrase), salt, { c: 310_000, dkLen: 32 }); const ciphertext = gcm(derivedKey, nonce).encrypt(utf8ToBytes(plainText));
  return { schema: "idlr-pts.encrypted-support-diagnostics.v1", algorithm: "AES-256-GCM", kdf: { algorithm: "PBKDF2-HMAC-SHA-256", iterations: 310_000, salt: bytesToHex(salt) }, nonce: bytesToHex(nonce), ciphertext: bytesToHex(ciphertext), note: "Share this package only through an authorized support case. Provide the passphrase through a separate approved channel." };
}
export async function decryptAuthorizedSupportDiagnostics(pkg: EncryptedSupportPackage, passphrase: string) { const { gcm, hexToBytes, bytesToUtf8, utf8ToBytes, pbkdf2, sha256 } = await dependencies(); if (pkg.algorithm !== "AES-256-GCM" || pkg.kdf.algorithm !== "PBKDF2-HMAC-SHA-256") throw new Error("Unsupported authorized support package format."); const key = pbkdf2(sha256, utf8ToBytes(passphrase), hexToBytes(pkg.kdf.salt), { c: pkg.kdf.iterations, dkLen: 32 }); return bytesToUtf8(gcm(key, hexToBytes(pkg.nonce)).decrypt(hexToBytes(pkg.ciphertext))); }
