-- Seed consent_records
INSERT INTO consent_records (organization_id, data_subject_name, data_subject_email, data_subject_nin, purpose, lawful_basis, consent_status, consent_given_at, expires_at, data_categories, processing_activities, third_party_sharing, cross_border_transfer) VALUES
(1, 'Adaeze Okonkwo', 'adaeze.okonkwo@gmail.com', '12345678901', 'Marketing communications and service updates', 'consent', 'active', NOW() - INTERVAL '30 days', NOW() + INTERVAL '1 year', '["name","email","phone"]', '["email_marketing","sms_alerts"]', false, false),
(1, 'Emeka Nwosu', 'emeka.nwosu@yahoo.com', '23456789012', 'Account registration and KYC verification', 'contract', 'active', NOW() - INTERVAL '60 days', NULL, '["name","email","bvn","nin","address"]', '["kyc_verification","account_management"]', false, false),
(2, 'Fatima Aliyu', 'fatima.aliyu@hotmail.com', '34567890123', 'Health insurance claims processing', 'legal_obligation', 'active', NOW() - INTERVAL '90 days', NULL, '["name","health_records","nin"]', '["claims_processing","fraud_detection"]', false, false),
(2, 'Chukwuemeka Obi', 'chukwuemeka.obi@gmail.com', '45678901234', 'Telecom service provisioning', 'contract', 'active', NOW() - INTERVAL '45 days', NULL, '["name","phone","location"]', '["service_delivery","billing"]', false, false),
(3, 'Ngozi Eze', 'ngozi.eze@gmail.com', '56789012345', 'Financial product recommendations', 'legitimate_interests', 'active', NOW() - INTERVAL '15 days', NOW() + INTERVAL '6 months', '["name","email","financial_data"]', '["analytics","product_recommendation"]', true, false),
(3, 'Babatunde Adeleke', 'babatunde.adeleke@gmail.com', '67890123456', 'Newsletter subscription', 'consent', 'withdrawn', NOW() - INTERVAL '120 days', NULL, '["name","email"]', '["newsletter"]', false, false),
(4, 'Aisha Mohammed', 'aisha.mohammed@gmail.com', '78901234567', 'Energy consumption analytics', 'legitimate_interests', 'active', NOW() - INTERVAL '20 days', NULL, '["name","address","consumption_data"]', '["analytics","billing"]', false, false),
(5, 'Oluwaseun Adeyemi', 'oluwaseun.adeyemi@gmail.com', '89012345678', 'Insurance policy management', 'contract', 'active', NOW() - INTERVAL '75 days', NULL, '["name","nin","health_records","address"]', '["policy_management","claims"]', false, false),
(1, 'Chidinma Okafor', 'chidinma.okafor@gmail.com', '90123456789', 'Fintech payment processing', 'contract', 'active', NOW() - INTERVAL '10 days', NULL, '["name","bvn","account_number"]', '["payment_processing","fraud_detection"]', false, false),
(2, 'Yusuf Ibrahim', 'yusuf.ibrahim@gmail.com', '01234567890', 'Data analytics for service improvement', 'legitimate_interests', 'active', NOW() - INTERVAL '50 days', NOW() + INTERVAL '2 years', '["usage_data","device_info"]', '["analytics","service_improvement"]', false, false);

-- Seed breach_incidents
INSERT INTO breach_incidents (organization_id, title, description, breach_incident_severity, breach_incident_status, detected_at, ndpc_notification_deadline, ndpc_notified_at, affected_individuals_count, data_types_affected, breach_cause, remediation_actions, ndpc_reference_number) VALUES
(1, 'Unauthorized Database Access - Customer PII Exposed', 'An external attacker gained unauthorized access to the customer database via SQL injection, exposing personal data of approximately 15,000 customers including names, emails, BVN numbers and addresses.', 'critical', 'ndpc_notified', NOW() - INTERVAL '5 days', NOW() - INTERVAL '2 days', NOW() - INTERVAL '2 days', 15000, '["name","email","bvn","address","phone"]', 'SQL injection vulnerability in legacy authentication module', 'Patched SQL injection vulnerability, rotated all database credentials, notified affected customers, engaged forensic investigation firm', 'NDPC/BR/2026/001'),
(2, 'Employee Laptop Theft - Customer Records', 'A company laptop containing unencrypted customer health records was stolen from an employee vehicle. The laptop contained records of approximately 3,200 policyholders.', 'high', 'individuals_notified', NOW() - INTERVAL '10 days', NOW() - INTERVAL '7 days', NOW() - INTERVAL '7 days', 3200, '["name","health_records","nin","address"]', 'Unencrypted laptop stolen from employee vehicle', 'Implemented mandatory full-disk encryption, remote wipe executed, affected individuals notified, police report filed', 'NDPC/BR/2026/002'),
(3, 'Third-Party API Data Leak', 'A misconfigured API endpoint at a third-party payment processor exposed transaction data for 8,500 customers over a 48-hour window before discovery.', 'high', 'contained', NOW() - INTERVAL '3 days', NOW() + INTERVAL '1 day', NULL, 8500, '["name","account_number","transaction_history"]', 'Misconfigured API authentication at third-party processor', 'API endpoint secured, third-party contract reviewed, data minimization measures implemented', NULL),
(4, 'Phishing Attack - Staff Credentials Compromised', 'A targeted phishing campaign compromised credentials of 3 staff members, potentially exposing access to customer energy consumption data.', 'medium', 'assessing', NOW() - INTERVAL '1 day', NOW() + INTERVAL '2 days', NULL, 500, '["name","address","consumption_data"]', 'Phishing email targeting finance department staff', 'Compromised accounts suspended, MFA enforced, security awareness training scheduled', NULL),
(5, 'Accidental Data Disclosure via Email', 'Customer data was accidentally included in a bulk email sent to wrong recipients due to a spreadsheet error.', 'low', 'resolved', NOW() - INTERVAL '20 days', NOW() - INTERVAL '17 days', NOW() - INTERVAL '17 days', 125, '["name","email","policy_number"]', 'Human error - wrong spreadsheet attached to bulk email', 'Affected customers notified, email recall attempted, process review completed, staff retrained', 'NDPC/BR/2026/003');

-- Seed dpo_appointments
INSERT INTO dpo_appointments (organization_id, dpo_name, dpo_email, dpo_phone, appointed_at, credential_status, dpco_id, dpco_name, certification_expires_at, independence_verified, training_hours_completed, is_active) VALUES
(1, 'Dr. Adaora Nwachukwu', 'adaora.nwachukwu@firstbank.com.ng', '+2348012345678', NOW() - INTERVAL '2 years', 'verified', 'DPCO-2024-001', 'DataShield Nigeria Ltd', NOW() + INTERVAL '1 year', true, 120, true),
(2, 'Engr. Musa Danjuma', 'musa.danjuma@mtn.com.ng', '+2348023456789', NOW() - INTERVAL '18 months', 'verified', 'DPCO-2024-002', 'PrivacyGuard Associates', NOW() + INTERVAL '8 months', true, 95, true),
(3, 'Mrs. Kemi Oladipo', 'kemi.oladipo@nhia.gov.ng', '+2348034567890', NOW() - INTERVAL '1 year', 'verified', 'DPCO-2024-003', 'CompliancePro Nigeria', NOW() + INTERVAL '6 months', true, 80, true),
(4, 'Mr. Chidi Eze', 'chidi.eze@nerc.gov.ng', '+2348045678901', NOW() - INTERVAL '6 months', 'pending', NULL, NULL, NULL, false, 40, true),
(5, 'Ms. Hauwa Bello', 'hauwa.bello@naicom.gov.ng', '+2348056789012', NOW() - INTERVAL '3 months', 'verified', 'DPCO-2024-005', 'DataShield Nigeria Ltd', NOW() + INTERVAL '2 years', true, 60, true),
(6, 'Dr. Tunde Fashola', 'tunde.fashola@accessbank.com.ng', '+2348067890123', NOW() - INTERVAL '9 months', 'verified', 'DPCO-2024-006', 'PrivacyGuard Associates', NOW() + INTERVAL '15 months', true, 110, true),
(7, 'Mrs. Ngozi Okonjo', 'ngozi.okonjo@gtbank.com.ng', '+2348078901234', NOW() - INTERVAL '14 months', 'expired', 'DPCO-2024-007', 'CompliancePro Nigeria', NOW() - INTERVAL '1 month', false, 75, false),
(8, 'Mr. Emeka Okafor', 'emeka.okafor@zenithbank.com.ng', '+2348089012345', NOW() - INTERVAL '4 months', 'pending', NULL, NULL, NULL, false, 25, true);

-- Seed ropa_records
INSERT INTO ropa_records (organization_id, processing_activity_name, controller_name, dpo_contact, purpose_of_processing, lawful_basis, data_categories, data_subjects, recipients, third_country_transfers, retention_period, security_measures, status) VALUES
(1, 'Customer KYC Verification', 'First Bank of Nigeria Plc', 'adaora.nwachukwu@firstbank.com.ng', 'Regulatory compliance - Know Your Customer verification per CBN guidelines', 'legal_obligation', '["name","address","nin","bvn","photo_id","date_of_birth"]', '["bank_customers","account_holders"]', '["CBN","NFIU","EFCC"]', false, '7 years post account closure', 'AES-256 encryption, access controls, audit logging', 'active'),
(1, 'Fraud Detection and Prevention', 'First Bank of Nigeria Plc', 'adaora.nwachukwu@firstbank.com.ng', 'Prevention of financial fraud and money laundering per EFCC Act', 'legal_obligation', '["transaction_data","device_fingerprint","ip_address","location"]', '["bank_customers"]', '["NFIU","EFCC","CBN"]', false, '10 years', 'ML fraud detection system, encrypted storage', 'active'),
(2, 'Subscriber Registration', 'MTN Nigeria Communications Plc', 'musa.danjuma@mtn.com.ng', 'SIM registration per NCC regulations and NIN linkage requirement', 'legal_obligation', '["name","nin","address","phone","photo"]', '["mobile_subscribers"]', '["NCC","NIMC"]', false, '5 years post subscription', 'Encrypted database, biometric verification', 'active'),
(3, 'Patient Health Records', 'NHIA', 'kemi.oladipo@nhia.gov.ng', 'Healthcare service delivery and insurance claims processing', 'vital_interests', '["health_records","diagnosis","treatment","medication","nin"]', '["nhia_enrollees","patients"]', '["healthcare_providers","FMOH"]', false, '25 years', 'Role-based access, encryption, audit trails', 'active'),
(4, 'Energy Consumption Monitoring', 'NERC', 'chidi.eze@nerc.gov.ng', 'Grid management and billing per Electricity Act 2023', 'legal_obligation', '["name","address","meter_data","consumption_data"]', '["electricity_consumers"]', '["DisCos","GenCos","TCN"]', false, '10 years', 'Encrypted SCADA systems, access controls', 'active'),
(5, 'Insurance Policyholder Data', 'NAICOM', 'hauwa.bello@naicom.gov.ng', 'Insurance policy management and claims processing', 'contract', '["name","nin","health_records","property_details","vehicle_info"]', '["policyholders"]', '["reinsurers","NAICOM"]', true, '10 years post policy expiry', 'Encrypted storage, DPA with reinsurers', 'active'),
(6, 'Fintech Transaction Processing', 'Access Bank Plc', 'tunde.fashola@accessbank.com.ng', 'Payment processing per CBN Open Banking guidelines', 'contract', '["name","bvn","account_number","transaction_history"]', '["bank_customers","fintech_users"]', '["CBN","NIBSS","payment_processors"]', false, '7 years', 'PCI-DSS compliance, tokenization, encryption', 'active'),
(7, 'Employee HR Records', 'GTBank Plc', 'ngozi.okonjo@gtbank.com.ng', 'Employment contract and payroll management', 'contract', '["name","nin","address","salary","tax_id","bank_details"]', '["employees"]', '["FIRS","PENCOM","NSITF"]', false, '7 years post employment', 'HR system access controls, encrypted payroll', 'active');

-- Seed retention_policies
INSERT INTO retention_policies (organization_id, policy_name, data_category, retention_period_days, legal_basis, deletion_method, is_active, review_date) VALUES
(1, 'Banking Transaction Records', 'financial_data', 2555, 'CBN Circular FPR/DIR/GEN/CIR/07/003 - 7 year retention requirement', 'secure_delete', true, NOW() + INTERVAL '1 year'),
(1, 'KYC Documents', 'identity_documents', 2555, 'EFCC Act 2004 and CBN AML/CFT regulations', 'secure_delete', true, NOW() + INTERVAL '1 year'),
(1, 'Audit Logs', 'system_logs', 1825, 'ISO 27001 and CBN IT Standards', 'secure_delete', true, NOW() + INTERVAL '6 months'),
(2, 'Subscriber Registration Data', 'personal_data', 1825, 'NCC Consumer Code of Practice 2007', 'secure_delete', true, NOW() + INTERVAL '1 year'),
(2, 'Call Detail Records', 'communications_data', 365, 'NCC Lawful Interception Regulations', 'secure_delete', true, NOW() + INTERVAL '6 months'),
(3, 'Patient Health Records', 'health_data', 9125, 'NHIA Act and FMOH Health Records Policy - 25 year retention', 'secure_delete', true, NOW() + INTERVAL '2 years'),
(4, 'Electricity Consumption Data', 'utility_data', 3650, 'NERC Grid Code and Metering Code', 'secure_delete', true, NOW() + INTERVAL '1 year'),
(5, 'Insurance Policy Records', 'insurance_data', 3650, 'NAICOM Insurance Act 2003 - 10 year retention', 'secure_delete', true, NOW() + INTERVAL '1 year'),
(6, 'Payment Transaction Logs', 'financial_data', 2555, 'CBN Payment System Management Act 2020', 'secure_delete', true, NOW() + INTERVAL '1 year'),
(1, 'Marketing Consent Records', 'consent_data', 365, 'NDPA 2023 - Consent withdrawal and record keeping', 'anonymize', true, NOW() + INTERVAL '6 months');

-- Seed dpo_reports
INSERT INTO dpo_reports (organization_id, dpo_appointment_id, report_period_start, report_period_end, status, activities_summary, violations_identified, dsars_handled, training_conducted, privacy_notices_review, recommendations, submitted_at) VALUES
(1, 1, NOW() - INTERVAL '6 months', NOW() - INTERVAL '3 months', 'submitted', 'Conducted quarterly privacy audit, reviewed 3 new data processing agreements, updated privacy notices for mobile banking app, coordinated response to 2 DSAR requests, delivered data protection training to 150 staff members.', 2, 8, 3, 'Privacy notices updated to reflect new mobile banking features and NDPA 2023 requirements', 'Recommend implementing automated DSAR tracking system, enhance third-party processor audit program', NOW() - INTERVAL '2 months'),
(2, 2, NOW() - INTERVAL '6 months', NOW() - INTERVAL '3 months', 'submitted', 'Reviewed NIN linkage compliance, conducted privacy impact assessment for new 5G rollout, handled 15 DSAR requests, updated data retention schedules, coordinated with NCC on lawful interception compliance.', 1, 15, 5, 'Privacy notices updated for 5G services and new data processing activities', 'Recommend enhanced encryption for CDR storage, implement automated data deletion workflows', NOW() - INTERVAL '2 months'),
(3, 3, NOW() - INTERVAL '3 months', NOW(), 'draft', 'Ongoing review of patient data localisation compliance, coordinating with healthcare providers on EMR data standards, reviewing cross-border data sharing with international health organizations.', 3, 5, 2, 'Privacy notices under review for telemedicine services', 'Urgent: implement data localisation controls for telemedicine platform, review international health data sharing agreements', NULL),
(1, 1, NOW() - INTERVAL '3 months', NOW(), 'submitted', 'Responded to data breach incident (NDPC/BR/2026/001), coordinated forensic investigation, notified 15,000 affected customers, implemented enhanced security controls, submitted breach notification to NDPC.', 5, 12, 8, 'Privacy notices updated post-breach to reflect enhanced security measures', 'Implement zero-trust architecture, enhance third-party security assessments, conduct annual penetration testing', NOW() - INTERVAL '1 week');

-- Seed adequacy_determinations
INSERT INTO adequacy_determinations (country_code, country_name, status, determination_date, review_date, ndpc_decision, conditions, applicable_sectors, is_active) VALUES
('GB', 'United Kingdom', 'adequate', NOW() - INTERVAL '2 years', NOW() + INTERVAL '1 year', 'The UK GDPR and Data Protection Act 2018 provide adequate protection equivalent to NDPA 2023 standards', 'Annual review required, monitoring of UK post-Brexit data protection developments', '["all"]', true),
('EU', 'European Union', 'adequate', NOW() - INTERVAL '3 years', NOW() + INTERVAL '6 months', 'EU GDPR provides adequate protection. Nigerian organizations may transfer data to EU member states without additional safeguards', 'Quarterly monitoring of CJEU decisions affecting data protection adequacy', '["all"]', true),
('US', 'United States', 'conditional', NOW() - INTERVAL '1 year', NOW() + INTERVAL '3 months', 'Transfers permitted only to US entities participating in the US-Nigeria Data Bridge framework or with appropriate safeguards (SCCs)', 'Must use Standard Contractual Clauses or Binding Corporate Rules. Financial sector transfers require CBN approval', '["banking","fintech","insurance"]', true),
('ZA', 'South Africa', 'adequate', NOW() - INTERVAL '18 months', NOW() + INTERVAL '18 months', 'POPIA provides adequate protection. ECOWAS data sharing framework applies', 'Monitor POPIA enforcement developments, annual review', '["all"]', true),
('CN', 'China', 'inadequate', NOW() - INTERVAL '6 months', NOW() + INTERVAL '6 months', 'China PIPL does not provide adequate protection equivalent to NDPA 2023. Transfers prohibited without explicit NDPC approval', 'Case-by-case approval required from NDPC. Enhanced due diligence mandatory', '["none"]', true),
('KE', 'Kenya', 'adequate', NOW() - INTERVAL '1 year', NOW() + INTERVAL '1 year', 'Kenya Data Protection Act 2019 provides adequate protection within ECOWAS framework', 'Annual review, monitoring of Kenya DPA enforcement', '["all"]', true),
('IN', 'India', 'conditional', NOW() - INTERVAL '3 months', NOW() + INTERVAL '9 months', 'India DPDP Act 2023 under review. Conditional adequacy pending full implementation assessment', 'Transfers permitted with Standard Contractual Clauses pending full adequacy determination', '["technology","fintech"]', true),
('AE', 'United Arab Emirates', 'conditional', NOW() - INTERVAL '8 months', NOW() + INTERVAL '4 months', 'UAE PDPL provides partial adequacy. Financial sector transfers require CBN and CBUAE coordination', 'Enhanced due diligence for financial data transfers, coordination with CBN required', '["banking","insurance","fintech"]', true);

-- Seed data_processing_agreements
INSERT INTO data_processing_agreements (organization_id, processor_name, processor_country, agreement_reference, processing_purposes, data_categories, status, signed_at, expires_at, sub_processors, security_measures, audit_rights) VALUES
(1, 'Interswitch Group', 'Nigeria', 'DPA-2024-ISW-001', '["payment_processing","fraud_detection","transaction_routing"]', '["account_number","bvn","transaction_data","device_info"]', 'active', NOW() - INTERVAL '1 year', NOW() + INTERVAL '1 year', '["Verve International","Quickteller"]', 'PCI-DSS Level 1, AES-256 encryption, HSM for key management, SOC 2 Type II certified', true),
(1, 'NIBSS Plc', 'Nigeria', 'DPA-2024-NIBSS-001', '["nip_processing","account_verification","bvn_validation"]', '["bvn","account_number","name","transaction_data"]', 'active', NOW() - INTERVAL '2 years', NOW() + INTERVAL '1 year', '[]', 'CBN-regulated infrastructure, ISO 27001 certified, dedicated private network', true),
(2, 'Ericsson Nigeria', 'Nigeria', 'DPA-2024-ERI-001', '["network_management","billing_system","subscriber_management"]', '["subscriber_data","call_records","location_data"]', 'active', NOW() - INTERVAL '18 months', NOW() + INTERVAL '6 months', '["Ericsson Sweden","Ericsson UK"]', 'ISO 27001, network segregation, encrypted data transmission', true),
(3, 'Sagicor Health', 'Nigeria', 'DPA-2024-SAG-001', '["claims_processing","health_analytics","fraud_detection"]', '["health_records","nin","policy_data","treatment_history"]', 'active', NOW() - INTERVAL '1 year', NOW() + INTERVAL '2 years', '[]', 'HIPAA-aligned controls, encrypted health records, role-based access', true),
(4, 'Siemens Energy Nigeria', 'Nigeria', 'DPA-2024-SIE-001', '["grid_monitoring","smart_meter_data","predictive_maintenance"]', '["consumption_data","meter_readings","address","account_data"]', 'active', NOW() - INTERVAL '6 months', NOW() + INTERVAL '2 years', '["Siemens Germany"]', 'IEC 62443 industrial cybersecurity, encrypted SCADA, VPN access only', true),
(5, 'Swiss Re Nigeria', 'Nigeria', 'DPA-2024-SWR-001', '["reinsurance_processing","risk_assessment","claims_management"]', '["policyholder_data","health_records","property_data","claims_history"]', 'active', NOW() - INTERVAL '1 year', NOW() + INTERVAL '1 year', '["Swiss Re Switzerland","Swiss Re UK"]', 'ISO 27001, GDPR compliant, SCCs for international transfers, annual audit rights', true),
(6, 'Flutterwave', 'Nigeria', 'DPA-2024-FLW-001', '["payment_gateway","fraud_detection","merchant_settlement"]', '["bvn","account_number","transaction_data","card_data"]', 'active', NOW() - INTERVAL '8 months', NOW() + INTERVAL '16 months', '["Visa","Mastercard"]', 'PCI-DSS Level 1, tokenization, 3DS2 authentication', true),
(1, 'Amazon Web Services', 'United States', 'DPA-2024-AWS-001', '["cloud_infrastructure","backup_storage","disaster_recovery"]', '["encrypted_data_backups","system_logs"]', 'active', NOW() - INTERVAL '2 years', NOW() + INTERVAL '1 year', '["AWS Ireland","AWS South Africa"]', 'ISO 27001, SOC 2 Type II, encryption at rest and in transit, data residency controls', true);

-- Seed privacy_notices
INSERT INTO privacy_notices (organization_id, notice_title, version, status, language, content, effective_date, review_date) VALUES
(1, 'First Bank Customer Privacy Notice', '3.2', 'published', 'en', 'This Privacy Notice explains how First Bank of Nigeria Plc ("First Bank", "we", "us") collects, uses, stores and protects your personal data in accordance with the Nigeria Data Protection Act 2023 (NDPA) and CBN regulations. We collect your data for account management, KYC compliance, fraud prevention, and service delivery. Your data is stored securely within Nigeria and shared only with regulatory authorities as required by law. You have rights to access, correct, delete and object to processing of your data. Contact our DPO at dpo@firstbank.com.ng for any privacy concerns.', NOW() - INTERVAL '3 months', NOW() + INTERVAL '9 months'),
(2, 'MTN Nigeria Subscriber Privacy Policy', '2.1', 'published', 'en', 'MTN Nigeria Communications Plc is committed to protecting your privacy. This policy describes how we collect and use your personal data including subscriber information, call records, location data and usage patterns. We process your data to provide telecommunications services, comply with NCC regulations, and improve our network. Your data is retained as required by NCC regulations. You have the right to access your data, request corrections, and lodge complaints with the NDPC. Contact privacy@mtn.com.ng for privacy inquiries.', NOW() - INTERVAL '6 months', NOW() + INTERVAL '6 months'),
(3, 'NHIA Enrollee Data Privacy Notice', '1.5', 'published', 'en', 'The National Health Insurance Authority (NHIA) processes your health and personal data to administer the National Health Insurance Scheme. This includes your health records, treatment history, and insurance claims. Your data is processed under legal obligation and vital interests basis. Health data is stored securely within Nigeria and shared only with accredited healthcare providers and FMOH as required. Contact our DPO at dpo@nhia.gov.ng for privacy rights requests.', NOW() - INTERVAL '1 year', NOW() + INTERVAL '6 months'),
(4, 'NERC Consumer Data Privacy Notice', '1.0', 'draft', 'en', 'The Nigerian Electricity Regulatory Commission (NERC) processes electricity consumer data including consumption records, meter data, and account information to regulate the electricity sector and ensure fair billing. Data is processed under legal obligation. Contact dpo@nerc.gov.ng for privacy inquiries.', NULL, NOW() + INTERVAL '3 months'),
(5, 'NAICOM Policyholder Privacy Notice', '2.0', 'published', 'en', 'The National Insurance Commission (NAICOM) processes policyholder data to regulate the insurance industry and protect policyholder interests. We process your insurance records, claims data, and personal information under legal obligation and contract. Your data is retained for 10 years as required by the Insurance Act. Contact dpo@naicom.gov.ng for privacy rights.', NOW() - INTERVAL '4 months', NOW() + INTERVAL '8 months');

-- Seed cookie_consent_records
INSERT INTO cookie_consent_records (organization_id, session_id, user_agent, ip_address, consent_given, analytics_cookies, marketing_cookies, functional_cookies, consent_version, consented_at) VALUES
(1, 'sess_abc123def456', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36', '197.210.54.123', true, true, false, true, '2.0', NOW() - INTERVAL '5 days'),
(1, 'sess_xyz789uvw012', 'Mozilla/5.0 (iPhone; CPU iPhone OS 16_0 like Mac OS X)', '197.210.54.124', true, false, false, true, '2.0', NOW() - INTERVAL '3 days'),
(2, 'sess_mno345pqr678', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)', '41.58.123.45', true, true, true, true, '1.5', NOW() - INTERVAL '7 days'),
(2, 'sess_stu901vwx234', 'Mozilla/5.0 (Linux; Android 12; SM-G998B)', '41.58.123.46', false, false, false, true, '1.5', NOW() - INTERVAL '2 days'),
(3, 'sess_yza567bcd890', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0)', '105.112.45.67', true, true, false, true, '1.0', NOW() - INTERVAL '10 days'),
(4, 'sess_efg123hij456', 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36', '154.120.78.90', true, false, false, true, '1.0', NOW() - INTERVAL '1 day'),
(5, 'sess_klm789nop012', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36', '197.211.45.23', true, true, true, true, '2.0', NOW() - INTERVAL '4 days'),
(1, 'sess_qrs345tuv678', 'Mozilla/5.0 (iPad; CPU OS 15_0 like Mac OS X)', '197.210.54.125', false, false, false, true, '2.0', NOW() - INTERVAL '6 days'),
(6, 'sess_wxy901zab234', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36', '41.58.200.12', true, true, false, true, '2.0', NOW() - INTERVAL '8 days'),
(7, 'sess_cde567fgh890', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 13_0)', '105.112.67.89', true, false, false, true, '1.5', NOW() - INTERVAL '12 days');

-- Seed automated_decision_records
INSERT INTO automated_decision_records (organization_id, system_name, decision_type, data_subject_ref, decision_outcome, logic_explanation, human_review_available, human_review_requested, objection_raised) VALUES
(1, 'CBN Credit Scoring Engine v3.2', 'credit_assessment', 'CUST-2024-001234', 'Credit limit set at NGN 500,000 based on risk score of 72/100', 'Score computed from: payment history (35%), credit utilization (30%), account age (15%), credit mix (10%), new inquiries (10%). Score of 72 indicates moderate-good creditworthiness.', true, false, false),
(1, 'AML Transaction Monitoring System', 'fraud_detection', 'ACCT-2024-056789', 'Transaction flagged for manual review - unusual pattern detected', 'Rule triggered: Transaction amount NGN 4.5M exceeds 3x average monthly transaction. Geographic anomaly: transaction initiated from IP in United Kingdom. Velocity check: 5 transactions in 2 hours.', true, true, false),
(2, 'NCC Network Quality Optimizer', 'service_quality', 'SUB-2024-789012', 'Data throttling applied to subscriber - fair usage policy triggered', 'Subscriber consumed 95% of monthly 50GB allocation in 18 days. Automated throttling to 1Mbps applied per NCC Fair Usage Policy. Full speed restored on billing cycle reset.', true, false, false),
(3, 'NHIA Claims Processing AI', 'insurance_claim', 'CLAIM-2024-345678', 'Claim approved for NGN 125,000 - within standard treatment protocol', 'Diagnosis code ICD-10 J18.9 (Pneumonia) matches approved treatment protocol. Hospital is NHIA-accredited. Claim amount within NGN 150,000 threshold for automated approval. No fraud indicators detected.', true, false, false),
(5, 'NAICOM Fraud Detection Engine', 'fraud_detection', 'CLAIM-2024-901234', 'Insurance claim flagged for investigation - fraud indicators detected', 'Multiple fraud indicators: (1) Claim submitted within 30 days of policy inception, (2) Claim amount equals policy sum insured, (3) Claimant has 2 prior claims in 12 months, (4) Vehicle registration mismatch detected.', true, true, true),
(6, 'CBN Open Banking Risk Engine', 'consent_decision', 'CONS-2024-567890', 'Third-party access request approved with enhanced monitoring', 'Fintech entity is CBN-licensed, NDPA-compliant, data minimization principles met. Access granted for 90 days with monthly review. Enhanced monitoring flag set due to cross-border data element.', true, false, false),
(1, 'Loan Origination System v2.1', 'loan_decision', 'CUST-2024-234567', 'Mortgage application declined - debt-to-income ratio exceeds threshold', 'Automated decline: DTI ratio of 52% exceeds CBN maximum of 40% for mortgage products. Monthly obligations NGN 185,000 against verified income of NGN 356,000. Applicant notified of right to human review.', true, true, false),
(4, 'Smart Grid Load Management AI', 'service_interruption', 'METER-2024-890123', 'Scheduled load shedding applied to zone 3 consumers', 'Grid frequency dropped to 49.2Hz (below 49.5Hz threshold). Automated load shedding activated for non-critical zones. Zone 3 selected based on: lowest priority classification, fewest medical/critical facilities, 4-hour rotation schedule.', true, false, false);

-- Seed parental_consent_records
INSERT INTO parental_consent_records (organization_id, child_ref, child_age, parent_guardian_name, parent_guardian_email, parent_guardian_nin, consent_purpose, consent_status, consent_given_at, verification_method, verified) VALUES
(1, 'CHILD-2024-001', 15, 'Mr. Emeka Okonkwo', 'emeka.okonkwo@gmail.com', '12345678901', 'Student savings account opening and mobile banking access', 'active', NOW() - INTERVAL '30 days', 'nin_verification', true),
(2, 'CHILD-2024-002', 14, 'Mrs. Fatima Bello', 'fatima.bello@yahoo.com', '23456789012', 'SIM card registration for educational purposes', 'active', NOW() - INTERVAL '45 days', 'nin_verification', true),
(1, 'CHILD-2024-003', 16, 'Dr. Chukwudi Eze', 'chukwudi.eze@gmail.com', '34567890123', 'Junior investment account and financial literacy app', 'active', NOW() - INTERVAL '20 days', 'biometric_verification', true),
(3, 'CHILD-2024-004', 13, 'Mrs. Amina Yusuf', 'amina.yusuf@gmail.com', '45678901234', 'NHIA family health insurance enrollment for minor', 'active', NOW() - INTERVAL '60 days', 'nin_verification', true),
(6, 'CHILD-2024-005', 17, 'Mr. Tunde Adeyemi', 'tunde.adeyemi@gmail.com', '56789012345', 'Fintech payment app for school fees and allowances', 'active', NOW() - INTERVAL '15 days', 'video_verification', true),
(1, 'CHILD-2024-006', 12, 'Mrs. Ngozi Okafor', 'ngozi.okafor@gmail.com', '67890123456', 'Children savings account', 'withdrawn', NOW() - INTERVAL '90 days', 'nin_verification', true),
(2, 'CHILD-2024-007', 15, 'Mr. Ibrahim Musa', 'ibrahim.musa@gmail.com', '78901234567', 'Educational content subscription and parental monitoring', 'active', NOW() - INTERVAL '10 days', 'nin_verification', true),
(5, 'CHILD-2024-008', 16, 'Mrs. Blessing Obi', 'blessing.obi@gmail.com', '89012345678', 'Life insurance policy for minor beneficiary', 'active', NOW() - INTERVAL '25 days', 'nin_verification', true);

-- Seed staff_training_records
INSERT INTO staff_training_records (organization_id, staff_name, staff_email, training_title, training_type, provider, completed_at, expires_at, score, passed, certificate_url) VALUES
(1, 'Adaeze Okonkwo', 'adaeze.okonkwo@firstbank.com.ng', 'NDPA 2023 Compliance for Banking Staff', 'data_protection', 'NDPC Training Academy', NOW() - INTERVAL '3 months', NOW() + INTERVAL '9 months', 88, true, 'https://ndpc.gov.ng/certs/NDPA-2024-FBN-001'),
(1, 'Emeka Nwosu', 'emeka.nwosu@firstbank.com.ng', 'AML/CFT Awareness Training', 'aml_cft', 'CAMS Nigeria', NOW() - INTERVAL '6 months', NOW() + INTERVAL '6 months', 92, true, 'https://cams.org/certs/AML-2024-FBN-002'),
(1, 'Fatima Aliyu', 'fatima.aliyu@firstbank.com.ng', 'Cybersecurity Fundamentals for Financial Institutions', 'cybersecurity', 'ISACA Nigeria', NOW() - INTERVAL '4 months', NOW() + INTERVAL '8 months', 85, true, 'https://isaca.org/certs/CISA-2024-FBN-003'),
(2, 'Musa Danjuma', 'musa.danjuma@mtn.com.ng', 'NCC Regulatory Compliance Training', 'regulatory', 'NCC Training Institute', NOW() - INTERVAL '2 months', NOW() + INTERVAL '10 months', 90, true, 'https://ncc.gov.ng/certs/NCC-2024-MTN-001'),
(2, 'Aisha Mohammed', 'aisha.mohammed@mtn.com.ng', 'Data Privacy for Telecom Professionals', 'data_protection', 'NDPC Training Academy', NOW() - INTERVAL '5 months', NOW() + INTERVAL '7 months', 78, true, 'https://ndpc.gov.ng/certs/NDPA-2024-MTN-002'),
(3, 'Kemi Oladipo', 'kemi.oladipo@nhia.gov.ng', 'Healthcare Data Protection and HIPAA Alignment', 'data_protection', 'FMOH Training Division', NOW() - INTERVAL '8 months', NOW() + INTERVAL '4 months', 95, true, 'https://fmoh.gov.ng/certs/HDP-2024-NHIA-001'),
(4, 'Chidi Eze', 'chidi.eze@nerc.gov.ng', 'NDPA 2023 for Government Agencies', 'data_protection', 'NDPC Training Academy', NOW() - INTERVAL '1 month', NOW() + INTERVAL '11 months', 82, true, 'https://ndpc.gov.ng/certs/NDPA-2024-NERC-001'),
(5, 'Hauwa Bello', 'hauwa.bello@naicom.gov.ng', 'Insurance Data Protection Best Practices', 'data_protection', 'NIA Training Institute', NOW() - INTERVAL '7 months', NOW() + INTERVAL '5 months', 88, true, 'https://nia.org.ng/certs/IDP-2024-NAICOM-001'),
(6, 'Tunde Fashola', 'tunde.fashola@accessbank.com.ng', 'Open Banking Security and Privacy', 'cybersecurity', 'CBN Academy', NOW() - INTERVAL '3 months', NOW() + INTERVAL '9 months', 91, true, 'https://cbn.gov.ng/certs/OBS-2024-ABP-001'),
(1, 'Chidinma Okafor', 'chidinma.okafor@firstbank.com.ng', 'GDPR and International Data Transfer Compliance', 'data_protection', 'IAPP Nigeria Chapter', NOW() - INTERVAL '10 months', NOW() + INTERVAL '2 months', 76, true, 'https://iapp.org/certs/GDPR-2024-FBN-004'),
(2, 'Babatunde Adeleke', 'babatunde.adeleke@mtn.com.ng', 'Incident Response and Breach Notification', 'cybersecurity', 'ISACA Nigeria', NOW() - INTERVAL '2 months', NOW() + INTERVAL '10 months', 88, true, 'https://isaca.org/certs/IR-2024-MTN-003'),
(7, 'Ngozi Okonjo', 'ngozi.okonjo@gtbank.com.ng', 'NDPA 2023 Compliance for Banking Staff', 'data_protection', 'NDPC Training Academy', NOW() - INTERVAL '14 months', NOW() - INTERVAL '2 months', 85, true, 'https://ndpc.gov.ng/certs/NDPA-2024-GTB-001');

-- Seed transfer_instruments
INSERT INTO transfer_instruments (organization_id, instrument_type, instrument_reference, destination_country, data_categories, status, approved_at, expires_at, conditions, ndpc_reference) VALUES
(1, 'standard_contractual_clauses', 'SCC-FBN-AWS-2024-001', 'United States', '["encrypted_backups","system_logs"]', 'active', NOW() - INTERVAL '1 year', NOW() + INTERVAL '1 year', 'Data must remain encrypted at all times. AWS Ireland as primary region. Annual security audit required.', 'NDPC/TI/2024/001'),
(1, 'binding_corporate_rules', 'BCR-FBN-GROUP-2024-001', 'United Kingdom', '["customer_data","transaction_records"]', 'active', NOW() - INTERVAL '2 years', NOW() + INTERVAL '1 year', 'First Bank Group BCR approved by NDPC. UK GDPR adequacy applies.', 'NDPC/TI/2024/002'),
(5, 'standard_contractual_clauses', 'SCC-NAICOM-SWR-2024-001', 'Switzerland', '["policyholder_data","claims_data","health_records"]', 'active', NOW() - INTERVAL '1 year', NOW() + INTERVAL '1 year', 'Swiss Re as reinsurer. FADP adequacy determination applies. Enhanced security measures for health data.', 'NDPC/TI/2024/003'),
(6, 'adequacy_decision', 'AD-ABP-UK-2024-001', 'United Kingdom', '["payment_data","transaction_records"]', 'active', NOW() - INTERVAL '6 months', NOW() + INTERVAL '18 months', 'UK GDPR adequacy applies. PCI-DSS compliance maintained.', 'NDPC/TI/2024/004'),
(3, 'standard_contractual_clauses', 'SCC-NHIA-WHO-2024-001', 'Switzerland', '["anonymized_health_statistics","epidemiology_data"]', 'active', NOW() - INTERVAL '8 months', NOW() + INTERVAL '16 months', 'Anonymized data only. WHO data sharing agreement. No individual-level data transfer.', 'NDPC/TI/2024/005'),
(2, 'adequacy_decision', 'AD-MTN-ZA-2024-001', 'South Africa', '["roaming_subscriber_data","interconnect_records"]', 'active', NOW() - INTERVAL '1 year', NOW() + INTERVAL '1 year', 'POPIA adequacy applies. MTN Group data sharing framework. Roaming data only.', 'NDPC/TI/2024/006');

-- Seed data_export_jobs
INSERT INTO data_export_jobs (organization_id, requested_by, export_type, data_categories, format, status, file_url, file_size_bytes, records_exported, started_at, completed_at, expires_at) VALUES
(1, 1, 'dsar_export', '["personal_data","transaction_history","consent_records"]', 'pdf', 'completed', 'https://storage.ndsep.gov.ng/exports/dsar-FBN-2024-001.pdf', 2457600, 1, NOW() - INTERVAL '5 days', NOW() - INTERVAL '5 days' + INTERVAL '2 minutes', NOW() + INTERVAL '25 days'),
(2, 1, 'compliance_report', '["subscriber_data","compliance_records","audit_logs"]', 'xlsx', 'completed', 'https://storage.ndsep.gov.ng/exports/compliance-MTN-2024-Q3.xlsx', 15728640, 45230, NOW() - INTERVAL '10 days', NOW() - INTERVAL '10 days' + INTERVAL '15 minutes', NOW() + INTERVAL '20 days'),
(3, 1, 'full_export', '["all_data"]', 'csv', 'processing', NULL, NULL, NULL, NOW() - INTERVAL '30 minutes', NULL, NOW() + INTERVAL '30 days'),
(4, 1, 'audit_export', '["audit_logs","access_logs","system_events"]', 'json', 'completed', 'https://storage.ndsep.gov.ng/exports/audit-NERC-2024-Q3.json', 8388608, 125000, NOW() - INTERVAL '3 days', NOW() - INTERVAL '3 days' + INTERVAL '8 minutes', NOW() + INTERVAL '27 days'),
(5, 1, 'dsar_export', '["personal_data","policy_records","claims_history"]', 'pdf', 'failed', NULL, NULL, NULL, NOW() - INTERVAL '2 days', NOW() - INTERVAL '2 days', NOW() + INTERVAL '28 days'),
(1, 1, 'breach_notification_export', '["breach_records","affected_individuals","notification_logs"]', 'pdf', 'completed', 'https://storage.ndsep.gov.ng/exports/breach-FBN-2026-001.pdf', 1048576, 15001, NOW() - INTERVAL '4 days', NOW() - INTERVAL '4 days' + INTERVAL '5 minutes', NOW() + INTERVAL '26 days');

-- Seed dcpmi_thresholds
INSERT INTO dcpmi_thresholds (metric_name, sector, threshold_value, unit, alert_level, is_active, description, regulatory_basis) VALUES
('Data Breach Notification Time', 'all', 72, 'hours', 'critical', true, 'Maximum time to notify NDPC of a personal data breach after detection', 'NDPA 2023 Section 40(1)'),
('DSAR Response Time', 'all', 30, 'days', 'warning', true, 'Maximum time to respond to a Data Subject Access Request', 'NDPA 2023 Section 34'),
('Privacy Notice Update Frequency', 'all', 365, 'days', 'warning', true, 'Maximum days between privacy notice reviews', 'NDPA 2023 Section 24'),
('DPO Training Hours', 'all', 40, 'hours_per_year', 'warning', true, 'Minimum annual training hours for Data Protection Officers', 'NDPC DPO Guidelines 2024'),
('Data Retention Compliance Rate', 'all', 95, 'percent', 'warning', true, 'Minimum percentage of data assets with compliant retention policies', 'NDPA 2023 Section 26'),
('KYC Completion Rate', 'banking', 100, 'percent', 'critical', true, 'All banking customers must complete KYC verification', 'CBN KYC/AML/CFT Regulations 2023'),
('AML Reporting Timeliness', 'banking', 24, 'hours', 'critical', true, 'Maximum time to file STR after suspicious transaction detection', 'EFCC Act 2004 and NFIU Guidelines'),
('NIN Linkage Rate', 'telecom', 100, 'percent', 'critical', true, 'All SIM cards must be linked to NIN', 'NCC SIM Registration Regulations 2022'),
('Data Localisation Compliance', 'healthcare', 100, 'percent', 'critical', true, 'Patient health records must be stored within Nigeria', 'NHIA Act and FMOH Data Policy'),
('Solvency Ratio Minimum', 'insurance', 150, 'percent', 'critical', true, 'Minimum solvency ratio for insurance companies', 'NAICOM Insurance Act 2003'),
('Open Banking Consent Validity', 'fintech', 90, 'days', 'warning', true, 'Maximum validity period for open banking consent without renewal', 'CBN Open Banking Policy 2021'),
('Grid Frequency Deviation', 'energy', 0.5, 'hz', 'critical', true, 'Maximum acceptable deviation from 50Hz grid frequency', 'NERC Grid Code 2023'),
('ROPA Review Frequency', 'all', 365, 'days', 'warning', true, 'Maximum days between ROPA (Record of Processing Activities) reviews', 'NDPA 2023 Section 29'),
('Consent Withdrawal Processing', 'all', 24, 'hours', 'warning', true, 'Maximum time to process consent withdrawal requests', 'NDPA 2023 Section 31'),
('Cross-Border Transfer Approval', 'all', 30, 'days', 'warning', true, 'Maximum time for NDPC to approve cross-border data transfer requests', 'NDPA 2023 Section 43');

-- Seed ndpa_compliance_snapshots
INSERT INTO ndpa_compliance_snapshots (organization_id, snapshot_date, overall_score, consent_score, breach_score, dpia_score, ropa_score, dpo_score, transfer_score, open_violations, critical_violations, pending_dsars, active_breaches) VALUES
(1, NOW() - INTERVAL '30 days', 78.5, 82.0, 65.0, 80.0, 85.0, 90.0, 75.0, 12, 2, 3, 1),
(1, NOW() - INTERVAL '60 days', 72.0, 78.0, 60.0, 75.0, 80.0, 88.0, 70.0, 18, 4, 5, 2),
(2, NOW() - INTERVAL '30 days', 85.0, 88.0, 82.0, 85.0, 90.0, 92.0, 80.0, 5, 0, 1, 0),
(2, NOW() - INTERVAL '60 days', 80.0, 85.0, 75.0, 82.0, 88.0, 90.0, 78.0, 8, 1, 2, 0),
(3, NOW() - INTERVAL '30 days', 70.0, 75.0, 68.0, 72.0, 78.0, 85.0, 62.0, 15, 3, 8, 2),
(4, NOW() - INTERVAL '30 days', 65.0, 70.0, 60.0, 68.0, 72.0, 78.0, 58.0, 20, 5, 4, 1),
(5, NOW() - INTERVAL '30 days', 80.0, 82.0, 78.0, 80.0, 85.0, 88.0, 76.0, 7, 1, 2, 0),
(NULL, NOW() - INTERVAL '30 days', 74.5, 79.0, 70.0, 76.0, 80.0, 87.0, 70.0, 77, 16, 23, 4),
(NULL, NOW() - INTERVAL '60 days', 70.0, 75.0, 65.0, 72.0, 76.0, 84.0, 66.0, 95, 22, 31, 7),
(NULL, NOW() - INTERVAL '90 days', 66.0, 71.0, 60.0, 68.0, 72.0, 80.0, 62.0, 112, 28, 38, 9);

