-- ============================================================
-- NDSEP DPCO Full Seed Data
-- Populates all 8 empty DPCO tables with realistic Nigerian data
-- Run: psql -U ndsep_user -d ndsep_db -h localhost -f seed-dpco-full.sql
-- ============================================================

BEGIN;

-- ── 1. DPCO Clients ──────────────────────────────────────────────────────────
INSERT INTO dpco_clients (dpco_org_id, org_name, org_sector, org_location, contact_name, contact_email, contact_phone, status, risk_level, compliance_score, onboarded_at, created_at, updated_at) VALUES
(1, 'First Bank of Nigeria Plc', 'banking', 'Lagos', 'Adaeze Okonkwo', 'adaeze.okonkwo@firstbank.ng', '+234-802-111-2222', 'active', 'medium', 74, NOW() - INTERVAL '18 months', NOW() - INTERVAL '18 months', NOW()),
(1, 'MTN Nigeria Communications Plc', 'telecommunications', 'Lagos', 'Emeka Chukwu', 'emeka.chukwu@mtn.ng', '+234-803-222-3333', 'active', 'high', 61, NOW() - INTERVAL '14 months', NOW() - INTERVAL '14 months', NOW()),
(1, 'Nigerian National Petroleum Corporation', 'energy', 'Abuja', 'Fatima Al-Hassan', 'fatima.alhassan@nnpc.gov.ng', '+234-805-333-4444', 'active', 'critical', 48, NOW() - INTERVAL '10 months', NOW() - INTERVAL '10 months', NOW()),
(1, 'Jumia Nigeria Ltd', 'e_commerce', 'Lagos', 'Chidi Eze', 'chidi.eze@jumia.com.ng', '+234-806-444-5555', 'active', 'medium', 82, NOW() - INTERVAL '8 months', NOW() - INTERVAL '8 months', NOW()),
(2, 'Access Bank Plc', 'banking', 'Lagos', 'Ngozi Adeyemi', 'ngozi.adeyemi@accessbank.ng', '+234-807-555-6666', 'active', 'medium', 79, NOW() - INTERVAL '16 months', NOW() - INTERVAL '16 months', NOW()),
(2, 'Airtel Nigeria Ltd', 'telecommunications', 'Lagos', 'Taiwo Oladele', 'taiwo.oladele@airtel.ng', '+234-808-666-7777', 'active', 'high', 65, NOW() - INTERVAL '12 months', NOW() - INTERVAL '12 months', NOW()),
(2, 'Lagos State Government', 'government', 'Lagos', 'Babatunde Fashola', 'b.fashola@lasgov.ng', '+234-809-777-8888', 'active', 'medium', 71, NOW() - INTERVAL '9 months', NOW() - INTERVAL '9 months', NOW()),
(3, 'Zenith Bank Plc', 'banking', 'Lagos', 'Amaka Obi', 'amaka.obi@zenithbank.ng', '+234-810-888-9999', 'active', 'low', 91, NOW() - INTERVAL '20 months', NOW() - INTERVAL '20 months', NOW()),
(3, 'Dangote Industries Ltd', 'manufacturing', 'Lagos', 'Ibrahim Musa', 'ibrahim.musa@dangote.com', '+234-811-999-0000', 'active', 'high', 58, NOW() - INTERVAL '7 months', NOW() - INTERVAL '7 months', NOW()),
(4, 'Nigerian Communications Commission', 'government', 'Abuja', 'Uche Nwosu', 'uche.nwosu@ncc.gov.ng', '+234-812-000-1111', 'active', 'low', 88, NOW() - INTERVAL '22 months', NOW() - INTERVAL '22 months', NOW()),
(4, 'Flutterwave Inc (Nigeria)', 'fintech', 'Lagos', 'Seun Adesanya', 'seun.adesanya@flutterwave.com', '+234-813-111-2222', 'active', 'medium', 76, NOW() - INTERVAL '11 months', NOW() - INTERVAL '11 months', NOW()),
(5, 'Guaranty Trust Bank Plc', 'banking', 'Lagos', 'Kemi Adeola', 'kemi.adeola@gtbank.ng', '+234-814-222-3333', 'active', 'low', 93, NOW() - INTERVAL '24 months', NOW() - INTERVAL '24 months', NOW()),
(5, 'Nigerian Breweries Plc', 'manufacturing', 'Lagos', 'Tunde Bakare', 'tunde.bakare@nigerianbrew.ng', '+234-815-333-4444', 'active', 'medium', 67, NOW() - INTERVAL '6 months', NOW() - INTERVAL '6 months', NOW()),
(5, 'Konga Online Shopping Ltd', 'e_commerce', 'Lagos', 'Yemi Osinbajo', 'yemi.osinbajo@konga.com', '+234-816-444-5555', 'inactive', 'low', 85, NOW() - INTERVAL '30 months', NOW() - INTERVAL '30 months', NOW());

-- ── 2. DPCO Audit Engagements ────────────────────────────────────────────────
INSERT INTO dpco_audit_engagements (dpco_org_id, client_id, title, current_stage, compliance_score, lead_auditor, planned_start, planned_end, actual_start, actual_end, critical_findings, high_findings, medium_findings, low_findings, management_response, notes, created_at, updated_at) VALUES
(1, 1, 'First Bank NDPA Annual Compliance Audit 2025', 'report_issued', 74, 'Dr. Chukwuemeka Obi', NOW() - INTERVAL '6 months', NOW() - INTERVAL '4 months', NOW() - INTERVAL '6 months', NOW() - INTERVAL '4 months', 0, 2, 5, 8, 'Management acknowledges findings and commits to remediation within 90 days. DPO appointed as action owner.', 'Audit completed on schedule. Key gap: data retention policy not formally documented.', NOW() - INTERVAL '7 months', NOW() - INTERVAL '4 months'),
(1, 2, 'MTN Nigeria Data Processing Audit Q3 2025', 'fieldwork', 61, 'Amaka Nwosu', NOW() - INTERVAL '3 months', NOW() - INTERVAL '1 month', NOW() - INTERVAL '3 months', NULL, 1, 4, 9, 12, NULL, 'Fieldwork ongoing. Subscriber data mapping exercise revealed undocumented third-party processors.', NOW() - INTERVAL '4 months', NOW()),
(1, 3, 'NNPC Data Sovereignty Compliance Review', 'gap_assessment', 48, 'Babatunde Adeyemi', NOW() - INTERVAL '2 months', NOW() + INTERVAL '2 months', NOW() - INTERVAL '2 months', NULL, 3, 6, 11, 7, NULL, 'Critical: cross-border data transfers to international partners not covered by adequacy decisions.', NOW() - INTERVAL '3 months', NOW()),
(2, 5, 'Access Bank NDPA Full Compliance Audit 2025', 'car_filed', 79, 'Ngozi Eze', NOW() - INTERVAL '9 months', NOW() - INTERVAL '6 months', NOW() - INTERVAL '9 months', NOW() - INTERVAL '6 months', 0, 1, 3, 6, 'All findings addressed. CAR filed with NDPC on 15 Nov 2025. Remediation verified.', 'Excellent cooperation from bank DPO team. Benchmark audit for banking sector.', NOW() - INTERVAL '10 months', NOW() - INTERVAL '5 months'),
(2, 6, 'Airtel Nigeria Subscriber Data Audit', 'findings_review', 65, 'Taiwo Oladele', NOW() - INTERVAL '4 months', NOW() - INTERVAL '1 month', NOW() - INTERVAL '4 months', NULL, 0, 3, 7, 10, 'Draft management response submitted. Final response expected by end of month.', 'Focus on SIM registration data and location data processing.', NOW() - INTERVAL '5 months', NOW()),
(3, 8, 'Zenith Bank ISO 27001 + NDPA Gap Analysis', 'report_issued', 91, 'Dr. Emeka Okafor', NOW() - INTERVAL '12 months', NOW() - INTERVAL '10 months', NOW() - INTERVAL '12 months', NOW() - INTERVAL '10 months', 0, 0, 1, 3, 'Minimal gaps identified. Bank maintains exemplary data governance posture.', 'Zenith Bank is a model for NDPA compliance in the banking sector.', NOW() - INTERVAL '13 months', NOW() - INTERVAL '9 months'),
(4, 10, 'NCC Regulatory Data Audit 2025', 'data_mapping', 88, 'Fatima Ibrahim', NOW() - INTERVAL '2 months', NOW() + INTERVAL '3 months', NOW() - INTERVAL '2 months', NULL, 0, 0, 2, 4, NULL, 'Data mapping of licensee databases in progress. 847 data assets identified so far.', NOW() - INTERVAL '3 months', NOW()),
(5, 12, 'GTBank NDPA Compliance Certification Audit', 'management_response', 93, 'Kemi Adeyemi', NOW() - INTERVAL '5 months', NOW() - INTERVAL '2 months', NOW() - INTERVAL '5 months', NOW() - INTERVAL '2 months', 0, 0, 0, 2, 'Management response submitted. Two minor observations on cookie consent banners addressed.', 'GTBank is pursuing NDPA Certification. Audit supports certification application.', NOW() - INTERVAL '6 months', NOW() - INTERVAL '1 month');

-- ── 3. DPCO Training Sessions ────────────────────────────────────────────────
INSERT INTO dpco_training_sessions (dpco_org_id, client_id, title, description, training_type, status, scheduled_date, completed_date, participant_count, certificates_issued, ndpa_section, facilitator, venue, created_at, updated_at) VALUES
(1, 1, 'NDPA Awareness Training for First Bank Staff', 'Comprehensive introduction to NDPA 2023 obligations for banking sector employees. Covers data subject rights, breach notification, and DPO responsibilities.', 'awareness', 'completed', NOW() - INTERVAL '5 months', NOW() - INTERVAL '5 months', 245, 245, 'Section 24-32', 'Dr. Chukwuemeka Obi', 'First Bank HQ, Lagos', NOW() - INTERVAL '6 months', NOW() - INTERVAL '4 months'),
(1, 2, 'MTN Data Protection Officer Certification', 'Advanced DPO certification programme covering NDPA compliance framework, DPIA methodology, breach response, and cross-border transfer rules.', 'dpo_certification', 'completed', NOW() - INTERVAL '4 months', NOW() - INTERVAL '4 months', 12, 12, 'Section 30-35', 'Amaka Nwosu', 'MTN Nigeria HQ, Lagos', NOW() - INTERVAL '5 months', NOW() - INTERVAL '3 months'),
(1, 3, 'NNPC Data Governance Workshop', 'Workshop on data governance frameworks, data classification, and cross-border transfer compliance for energy sector.', 'workshop', 'in_progress', NOW() - INTERVAL '1 month', NULL, 38, 0, 'Section 41-45', 'Babatunde Adeyemi', 'NNPC Towers, Abuja', NOW() - INTERVAL '2 months', NOW()),
(2, 5, 'Access Bank Privacy by Design Training', 'Technical training for IT and product teams on implementing privacy by design principles in banking systems.', 'technical', 'completed', NOW() - INTERVAL '7 months', NOW() - INTERVAL '7 months', 67, 67, 'Section 24', 'Ngozi Eze', 'Access Bank IT Centre, Lagos', NOW() - INTERVAL '8 months', NOW() - INTERVAL '6 months'),
(2, 7, 'Lagos State Government NDPA Compliance Bootcamp', '3-day intensive bootcamp for government MDAs on NDPA obligations, citizen data rights, and e-government data protection.', 'bootcamp', 'scheduled', NOW() + INTERVAL '2 weeks', NULL, 0, 0, 'Section 24-48', 'Taiwo Oladele', 'Lagos House, Ikeja', NOW() - INTERVAL '1 month', NOW()),
(3, 9, 'Dangote Industries Data Classification Workshop', 'Hands-on workshop for identifying and classifying personal data across manufacturing operations, supply chain, and HR systems.', 'workshop', 'completed', NOW() - INTERVAL '3 months', NOW() - INTERVAL '3 months', 89, 89, 'Section 24-28', 'Dr. Emeka Okafor', 'Dangote HQ, Lagos', NOW() - INTERVAL '4 months', NOW() - INTERVAL '2 months'),
(4, 11, 'Flutterwave NDPA + PCI-DSS Integration Training', 'Specialised training on aligning NDPA obligations with PCI-DSS requirements for fintech payment processors.', 'technical', 'scheduled', NOW() + INTERVAL '1 month', NULL, 0, 0, 'Section 24-35', 'Fatima Ibrahim', 'Flutterwave Office, Lagos', NOW() - INTERVAL '2 weeks', NOW()),
(5, 12, 'GTBank Board-Level Privacy Governance Briefing', 'Executive briefing for GTBank board and senior management on NDPA accountability obligations, penalties, and governance.', 'executive', 'completed', NOW() - INTERVAL '8 months', NOW() - INTERVAL '8 months', 18, 0, 'Section 48-55', 'Kemi Adeyemi', 'GTBank HQ, Lagos', NOW() - INTERVAL '9 months', NOW() - INTERVAL '7 months');

-- ── 4. DPCO Verification Statements ─────────────────────────────────────────
INSERT INTO dpco_verification_statements (dpco_org_id, client_org_id, client_name, filing_period, statement_type, statement_text, signed_by, signed_at, verification_code, status, submitted_at, created_at, updated_at) VALUES
(1, 1, 'First Bank of Nigeria Plc', '2024-Q4', 'compliance_audit_return', 'DataGuard Nigeria Ltd hereby certifies that First Bank of Nigeria Plc has been audited against the Nigeria Data Protection Act 2023 and associated regulations. The organisation demonstrates adequate data protection controls with a compliance score of 74/100. Key findings have been communicated to management and a corrective action register has been established.', 'Dr. Chukwuemeka Obi', NOW() - INTERVAL '4 months', 'VS-2024-Q4-FBN-001', 'submitted', NOW() - INTERVAL '4 months', NOW() - INTERVAL '5 months', NOW()),
(1, 2, 'MTN Nigeria Communications Plc', '2025-Q1', 'dpo_report', 'This DPO Report certifies that MTN Nigeria Communications Plc has appointed a qualified Data Protection Officer and has implemented data protection policies in accordance with NDPA 2023 Section 30. The DPO has conducted internal audits and reported findings to the Board Privacy Committee.', 'Amaka Nwosu', NOW() - INTERVAL '2 months', 'VS-2025-Q1-MTN-002', 'submitted', NOW() - INTERVAL '2 months', NOW() - INTERVAL '3 months', NOW()),
(2, 5, 'Access Bank Plc', '2024-Q4', 'compliance_audit_return', 'SecureData Services certifies that Access Bank Plc has achieved a compliance score of 79/100 under the NDPA 2023 framework. The bank has implemented robust data governance policies, appointed a DPO, and established a data breach response team. Corrective Action Report filed with NDPC.', 'Ngozi Eze', NOW() - INTERVAL '5 months', 'VS-2024-Q4-ABP-003', 'submitted', NOW() - INTERVAL '5 months', NOW() - INTERVAL '6 months', NOW()),
(3, 8, 'Zenith Bank Plc', '2025-Q1', 'compliance_audit_return', 'ComplianceFirst Ltd certifies that Zenith Bank Plc has achieved an exceptional compliance score of 91/100, making it one of the highest-performing financial institutions under the NDPA 2023 framework. The bank maintains comprehensive data governance, privacy-by-design practices, and proactive breach management.', 'Dr. Emeka Okafor', NOW() - INTERVAL '9 months', 'VS-2025-Q1-ZBP-004', 'submitted', NOW() - INTERVAL '9 months', NOW() - INTERVAL '10 months', NOW()),
(5, 12, 'Guaranty Trust Bank Plc', '2024-Q3', 'compliance_audit_return', 'DataTrust Consulting certifies that Guaranty Trust Bank Plc has achieved a compliance score of 93/100, the highest in the banking sector. GTBank demonstrates exemplary data protection practices and is recommended for NDPA Certification by the NDPC.', 'Kemi Adeyemi', NOW() - INTERVAL '2 months', 'VS-2024-Q3-GTB-005', 'submitted', NOW() - INTERVAL '2 months', NOW() - INTERVAL '3 months', NOW());

-- ── 5. DPCO Policy Drafts ────────────────────────────────────────────────────
INSERT INTO dpco_policy_drafts (dpco_org_id, client_org_id, client_name, title, document_type, content, version, status, created_at, updated_at) VALUES
(1, 1, 'First Bank of Nigeria Plc', 'First Bank Data Protection Policy v2.1', 'data_protection_policy', 'This Data Protection Policy establishes the framework for how First Bank of Nigeria Plc collects, processes, stores, and protects personal data in accordance with the Nigeria Data Protection Act 2023 (NDPA). The policy applies to all employees, contractors, and third-party processors handling personal data on behalf of the bank. Key principles: lawfulness, fairness, transparency, purpose limitation, data minimisation, accuracy, storage limitation, integrity and confidentiality, and accountability.', '2.1', 'signed', NOW() - INTERVAL '4 months', NOW() - INTERVAL '3 months'),
(1, 2, 'MTN Nigeria Communications Plc', 'MTN Nigeria Privacy Notice (Subscriber Data)', 'privacy_notice', 'MTN Nigeria Communications Plc (MTN) is committed to protecting the privacy and personal data of our subscribers. This Privacy Notice explains how we collect, use, share, and protect your personal data when you use our telecommunications services. We process subscriber data for service delivery, billing, fraud prevention, regulatory compliance, and network management. You have rights to access, correct, delete, and port your data.', '1.3', 'reviewed', NOW() - INTERVAL '3 months', NOW() - INTERVAL '2 months'),
(2, 5, 'Access Bank Plc', 'Access Bank Data Retention and Disposal Policy', 'retention_policy', 'This policy establishes the retention schedules and disposal procedures for personal data processed by Access Bank Plc. Financial records: 7 years post-account closure. KYC data: 5 years post-relationship end. Transaction data: 5 years. Marketing data: 2 years or until consent withdrawn. Biometric data: deleted immediately upon account closure. All disposal must be certified and logged.', '1.0', 'approved_by', NOW() - INTERVAL '6 months', NOW() - INTERVAL '5 months'),
(3, 8, 'Zenith Bank Plc', 'Zenith Bank Cross-Border Data Transfer Policy', 'transfer_policy', 'This policy governs the transfer of personal data from Nigeria to foreign countries by Zenith Bank Plc. All cross-border transfers must be covered by: (a) an adequacy decision by the NDPC, (b) appropriate safeguards such as standard contractual clauses, or (c) explicit consent of the data subject. The bank maintains a register of all cross-border transfers and conducts annual Transfer Impact Assessments.', '2.0', 'signed', NOW() - INTERVAL '10 months', NOW() - INTERVAL '9 months'),
(4, 11, 'Flutterwave Inc (Nigeria)', 'Flutterwave Payment Data Processing Agreement', 'data_processing_agreement', 'This Data Processing Agreement (DPA) governs the processing of personal data by Flutterwave Inc as a data processor on behalf of merchant clients. Flutterwave commits to: processing data only on documented instructions, implementing appropriate technical and organisational security measures, assisting with data subject rights requests, notifying breaches within 72 hours, and deleting data upon contract termination.', '1.1', 'draft', NOW() - INTERVAL '1 month', NOW()),
(5, 12, 'Guaranty Trust Bank Plc', 'GTBank Employee Data Protection Policy', 'employee_privacy_policy', 'This policy governs the processing of employee personal data by Guaranty Trust Bank Plc. Employee data is processed for HR administration, payroll, performance management, access control, and legal compliance. Employees have rights to access their data, correct inaccuracies, and object to certain processing. Biometric data for access control is processed under legitimate interest with appropriate safeguards.', '1.2', 'signed', NOW() - INTERVAL '8 months', NOW() - INTERVAL '7 months');

-- ── 6. DPCO Evidence Items ───────────────────────────────────────────────────
INSERT INTO dpco_evidence_items (dpco_org_id, client_id, title, description, file_url, file_key, file_name, mime_type, file_size, sha256_hash, control_ids, status, uploaded_by, created_at, updated_at) VALUES
(1, 1, 'First Bank DPO Appointment Letter', 'Formal appointment letter for First Bank Data Protection Officer, signed by MD/CEO', 'https://storage.ndsep.ng/evidence/fbN-dpo-appointment-2024.pdf', 'evidence/fbn-dpo-appointment-2024.pdf', 'FBN-DPO-Appointment-2024.pdf', 'application/pdf', 245678, 'a1b2c3d4e5f6789012345678901234567890abcdef1234567890abcdef123456', ARRAY['CTRL-001','CTRL-002'], 'active', 'Dr. Chukwuemeka Obi', NOW() - INTERVAL '5 months', NOW()),
(1, 1, 'First Bank Data Processing Register', 'Article 30 Record of Processing Activities (RoPA) — 847 processing activities documented', 'https://storage.ndsep.ng/evidence/fbn-ropa-2024.xlsx', 'evidence/fbn-ropa-2024.xlsx', 'FBN-RoPA-2024.xlsx', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 1234567, 'b2c3d4e5f6789012345678901234567890abcdef1234567890abcdef1234567a', ARRAY['CTRL-003','CTRL-004'], 'active', 'Dr. Chukwuemeka Obi', NOW() - INTERVAL '5 months', NOW()),
(1, 2, 'MTN Nigeria Privacy Policy (Published)', 'Published privacy policy accessible at mtn.ng/privacy — covers all subscriber data processing', 'https://storage.ndsep.ng/evidence/mtn-privacy-policy-2025.pdf', 'evidence/mtn-privacy-policy-2025.pdf', 'MTN-Privacy-Policy-2025.pdf', 'application/pdf', 567890, 'c3d4e5f6789012345678901234567890abcdef1234567890abcdef1234567ab2', ARRAY['CTRL-005','CTRL-006'], 'active', 'Amaka Nwosu', NOW() - INTERVAL '3 months', NOW()),
(2, 5, 'Access Bank Breach Response Procedure', 'Documented data breach response procedure including 72-hour notification protocol', 'https://storage.ndsep.ng/evidence/access-breach-procedure-2024.pdf', 'evidence/access-breach-procedure-2024.pdf', 'Access-Breach-Procedure-2024.pdf', 'application/pdf', 345678, 'd4e5f6789012345678901234567890abcdef1234567890abcdef1234567ab2c3', ARRAY['CTRL-007','CTRL-008'], 'active', 'Ngozi Eze', NOW() - INTERVAL '7 months', NOW()),
(3, 8, 'Zenith Bank ISO 27001 Certificate', 'ISO 27001:2022 certification from BSI Group, valid until 2026', 'https://storage.ndsep.ng/evidence/zenith-iso27001-cert-2024.pdf', 'evidence/zenith-iso27001-cert-2024.pdf', 'Zenith-ISO27001-Cert-2024.pdf', 'application/pdf', 123456, 'e5f6789012345678901234567890abcdef1234567890abcdef1234567ab2c3d4', ARRAY['CTRL-009','CTRL-010'], 'active', 'Dr. Emeka Okafor', NOW() - INTERVAL '11 months', NOW()),
(5, 12, 'GTBank DPIA for Mobile Banking App', 'Data Protection Impact Assessment for GTBank mobile banking application v4.2', 'https://storage.ndsep.ng/evidence/gtbank-dpia-mobile-2025.pdf', 'evidence/gtbank-dpia-mobile-2025.pdf', 'GTBank-DPIA-Mobile-2025.pdf', 'application/pdf', 789012, 'f6789012345678901234567890abcdef1234567890abcdef1234567ab2c3d4e5', ARRAY['CTRL-011','CTRL-012'], 'active', 'Kemi Adeyemi', NOW() - INTERVAL '6 months', NOW());

-- ── 7. DPCO Audit Control Ratings ────────────────────────────────────────────
INSERT INTO dpco_audit_control_ratings (engagement_id, control_id, rating, notes, rated_by, rated_at, created_at, updated_at) VALUES
(1, 'CTRL-001', 'compliant', 'DPO formally appointed with direct board reporting line. Adequate resources allocated.', 'Dr. Chukwuemeka Obi', NOW() - INTERVAL '4 months', NOW() - INTERVAL '4 months', NOW()),
(1, 'CTRL-002', 'partial', 'RoPA maintained but 12% of processing activities lack documented legal basis.', 'Dr. Chukwuemeka Obi', NOW() - INTERVAL '4 months', NOW() - INTERVAL '4 months', NOW()),
(1, 'CTRL-003', 'compliant', 'DSR portal operational. Average response time 8 days (within 30-day limit).', 'Dr. Chukwuemeka Obi', NOW() - INTERVAL '4 months', NOW() - INTERVAL '4 months', NOW()),
(1, 'CTRL-004', 'partial', 'Breach procedure documented but not tested via tabletop exercise in last 12 months.', 'Dr. Chukwuemeka Obi', NOW() - INTERVAL '4 months', NOW() - INTERVAL '4 months', NOW()),
(1, 'CTRL-005', 'non_compliant', '34 of 127 third-party processors lack current DPAs. Remediation plan required.', 'Dr. Chukwuemeka Obi', NOW() - INTERVAL '4 months', NOW() - INTERVAL '4 months', NOW()),
(4, 'CTRL-001', 'compliant', 'DPO appointed 3 years ago. Certified CIPP/E and CIPM. Full board access.', 'Ngozi Eze', NOW() - INTERVAL '5 months', NOW() - INTERVAL '5 months', NOW()),
(4, 'CTRL-002', 'compliant', 'Comprehensive RoPA with 1,243 processing activities. Reviewed quarterly.', 'Ngozi Eze', NOW() - INTERVAL '5 months', NOW() - INTERVAL '5 months', NOW()),
(4, 'CTRL-003', 'compliant', 'Dedicated DSR team. 100% on-time response rate in last 6 months.', 'Ngozi Eze', NOW() - INTERVAL '5 months', NOW() - INTERVAL '5 months', NOW()),
(6, 'CTRL-001', 'compliant', 'Zenith Bank DPO is a model for the industry. Full independence, dedicated budget.', 'Dr. Emeka Okafor', NOW() - INTERVAL '9 months', NOW() - INTERVAL '9 months', NOW()),
(6, 'CTRL-002', 'compliant', 'RoPA covers 2,891 processing activities. Automated updates via data discovery tool.', 'Dr. Emeka Okafor', NOW() - INTERVAL '9 months', NOW() - INTERVAL '9 months', NOW()),
(6, 'CTRL-003', 'compliant', 'AI-powered DSR portal. Average response time 3 days.', 'Dr. Emeka Okafor', NOW() - INTERVAL '9 months', NOW() - INTERVAL '9 months', NOW()),
(6, 'CTRL-004', 'compliant', 'Breach response team tested quarterly. 72-hour notification SLA consistently met.', 'Dr. Emeka Okafor', NOW() - INTERVAL '9 months', NOW() - INTERVAL '9 months', NOW());

-- ── 8. DPCO Engagement Requests ──────────────────────────────────────────────
INSERT INTO dpco_engagement_requests (dpco_org_id, org_name, org_sector, org_country, contact_name, contact_email, contact_phone, audit_scope, status, reference_token, created_at, updated_at) VALUES
(1, 'Dangote Industries Ltd', 'manufacturing', 'Nigeria', 'Ibrahim Musa', 'privacy@dangote.com', '+234-811-999-0000', 'Full NDPA compliance audit for manufacturing operations covering 45,000 employees and 2.3M customers across cement, sugar, and flour divisions.', 'accepted', gen_random_uuid()::text, NOW() - INTERVAL '4 months', NOW() - INTERVAL '3 months'),
(1, 'Nigerian Breweries Plc', 'manufacturing', 'Nigeria', 'Tunde Bakare', 'dpo@nigerianbrew.ng', '+234-815-333-4444', 'NDPA awareness training for 1,200 employees across Lagos and Aba breweries. Focus on marketing and HR teams.', 'pending', gen_random_uuid()::text, NOW() - INTERVAL '2 weeks', NOW()),
(2, 'Flutterwave Inc (Nigeria)', 'fintech', 'Nigeria', 'Seun Adesanya', 'legal@flutterwave.com', '+234-813-111-2222', 'Advisory on cross-border data transfer compliance under NDPA for expansion to Ghana, Kenya, South Africa, Rwanda, and Egypt.', 'accepted', gen_random_uuid()::text, NOW() - INTERVAL '3 months', NOW() - INTERVAL '2 months'),
(3, 'Dangote Industries Ltd', 'manufacturing', 'Nigeria', 'Ibrahim Musa', 'privacy@dangote.com', '+234-811-999-0000', 'Policy drafting: employee privacy policy, customer data policy, CCTV policy, and third-party processor management policy.', 'converted', gen_random_uuid()::text, NOW() - INTERVAL '5 months', NOW() - INTERVAL '4 months'),
(4, 'Lagos State Government', 'government', 'Nigeria', 'Babatunde Fashola', 'dataprotection@lasgov.ng', '+234-809-777-8888', 'Outsourced DPO function for 23 MDAs. Shared DPO role across state government with expertise in government data processing and citizen rights.', 'pending', gen_random_uuid()::text, NOW() - INTERVAL '1 week', NOW()),
(5, 'Konga Online Shopping Ltd', 'e_commerce', 'Nigeria', 'Yemi Osinbajo', 'privacy@konga.com', '+234-816-444-5555', 'Breach support: assessment, NDPC notification, customer communication, and remediation for breach affecting 127,000 customer accounts.', 'accepted', gen_random_uuid()::text, NOW() - INTERVAL '6 months', NOW() - INTERVAL '5 months');

COMMIT;

-- Verify seeding
SELECT 
  'dpco_clients' AS tbl, COUNT(*) AS cnt FROM dpco_clients
UNION ALL SELECT 'dpco_audit_engagements', COUNT(*) FROM dpco_audit_engagements
UNION ALL SELECT 'dpco_training_sessions', COUNT(*) FROM dpco_training_sessions
UNION ALL SELECT 'dpco_verification_statements', COUNT(*) FROM dpco_verification_statements
UNION ALL SELECT 'dpco_policy_drafts', COUNT(*) FROM dpco_policy_drafts
UNION ALL SELECT 'dpco_evidence_items', COUNT(*) FROM dpco_evidence_items
UNION ALL SELECT 'dpco_audit_control_ratings', COUNT(*) FROM dpco_audit_control_ratings
UNION ALL SELECT 'dpco_engagement_requests', COUNT(*) FROM dpco_engagement_requests
ORDER BY tbl;
