#!/usr/bin/env bash
set -euo pipefail

# Pre-production-only provider acknowledgment-loss gate.
# Default mode is a non-mutating preflight. Execute requires explicit confirmation.
# The provider test harness must be configured to drop the response after its durable
# commit; this script never infers provider state from the dropped HTTP response.

MODE=preflight
CONFIRM=""
POLL_SECONDS="${POLL_SECONDS:-5}"
POLL_ATTEMPTS="${POLL_ATTEMPTS:-24}"

usage() {
  cat <<'EOF'
Usage:
  validate_live_provider_ack_loss_preprod.sh --preflight
  validate_live_provider_ack_loss_preprod.sh --execute --confirm LIVE_ACK_LOSS_PREPROD

Required environment:
  DATABASE_URL                  Pre-production PostgreSQL URL
  TEST_MUTATION_URL             Approved pre-production mutation endpoint
  TEST_MUTATION_PAYLOAD_FILE    Test-only payload file with no production identifiers
  ACK_LOSS_TEST_HOOK_URL        Provider test harness endpoint, pre-production only
  ACK_LOSS_TEST_HOOK_TOKEN      Secret-manager token for the test harness
  TIGERBEETLE_LOOKUP_URL        Approved immutable-reference lookup endpoint
  MOJALOOP_LOOKUP_URL           Approved immutable-reference lookup endpoint
  PROVIDER_LOOKUP_TOKEN         Secret-manager lookup token
  TEST_TRANSFER_REFERENCE       Unique test reference, generated by the test owner
  TEST_ACTOR_ID                 Test actor identity
EOF
}

while (($#)); do
  case "$1" in
    --preflight) MODE=preflight ;;
    --execute) MODE=execute ;;
    --confirm) shift; CONFIRM="${1:-}" ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage >&2; exit 2 ;;
  esac
  shift
done

: "${DATABASE_URL:?DATABASE_URL is required}"
: "${TEST_MUTATION_URL:?TEST_MUTATION_URL is required}"
: "${TEST_MUTATION_PAYLOAD_FILE:?TEST_MUTATION_PAYLOAD_FILE is required}"
: "${ACK_LOSS_TEST_HOOK_URL:?ACK_LOSS_TEST_HOOK_URL is required}"
: "${ACK_LOSS_TEST_HOOK_TOKEN:?ACK_LOSS_TEST_HOOK_TOKEN is required}"
: "${TIGERBEETLE_LOOKUP_URL:?TIGERBEETLE_LOOKUP_URL is required}"
: "${MOJALOOP_LOOKUP_URL:?MOJALOOP_LOOKUP_URL is required}"
: "${PROVIDER_LOOKUP_TOKEN:?PROVIDER_LOOKUP_TOKEN is required}"
: "${TEST_TRANSFER_REFERENCE:?TEST_TRANSFER_REFERENCE is required}"
: "${TEST_ACTOR_ID:?TEST_ACTOR_ID is required}"

command -v curl >/dev/null || { echo "curl is required" >&2; exit 1; }
command -v psql >/dev/null || { echo "psql is required" >&2; exit 1; }
[[ -s "$TEST_MUTATION_PAYLOAD_FILE" ]] || { echo "test payload file is empty" >&2; exit 1; }
[[ "$ACK_LOSS_TEST_HOOK_URL" == https://*preprod* ]] || { echo "refusing non-preprod ACK_LOSS_TEST_HOOK_URL" >&2; exit 1; }
[[ "$TIGERBEETLE_LOOKUP_URL" == https://*preprod* ]] || { echo "refusing non-preprod TigerBeetle URL" >&2; exit 1; }
[[ "$MOJALOOP_LOOKUP_URL" == https://*preprod* ]] || { echo "refusing non-preprod Mojaloop URL" >&2; exit 1; }

printf '%s\n' '== Preflight: no transfer mutation =='
psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -Atc \
  "SELECT current_database(), current_user; SELECT count(*) FROM financial_transfer_outbox WHERE transfer_reference = '$TEST_TRANSFER_REFERENCE';"
for endpoint in "$ACK_LOSS_TEST_HOOK_URL/health" "$TIGERBEETLE_LOOKUP_URL/health" "$MOJALOOP_LOOKUP_URL/health"; do
  curl --fail --silent --show-error --max-time 10 "$endpoint" >/dev/null
  printf 'healthy %s\n' "$endpoint"
done

if [[ "$MODE" == preflight ]]; then
  echo 'PREFLIGHT ONLY: provider fault injection and mutation were not executed.'
  exit 0
fi

[[ "$CONFIRM" == LIVE_ACK_LOSS_PREPROD ]] || {
  echo 'Refusing execute: pass --confirm LIVE_ACK_LOSS_PREPROD' >&2
  exit 1
}

printf '%s\n' '== Configure provider harness: commit then drop response =='
curl --fail --silent --show-error --max-time 15 \
  -H "authorization: Bearer $ACK_LOSS_TEST_HOOK_TOKEN" \
  -H 'content-type: application/json' \
  --data "{\"reference\":\"$TEST_TRANSFER_REFERENCE\",\"mode\":\"commit_then_drop_response\",\"provider\":\"tigerbeetle\"}" \
  "$ACK_LOSS_TEST_HOOK_URL/v1/scenarios/ack-loss" >/dev/null

printf '%s\n' '== Initiate exactly one test intent =='
curl --fail-with-body --silent --show-error --max-time 15 \
  -H "x-test-actor-id: $TEST_ACTOR_ID" \
  -H 'content-type: application/json' \
  --data-binary "@$TEST_MUTATION_PAYLOAD_FILE" \
  "$TEST_MUTATION_URL" >/tmp/ndsep-ack-loss-initiation.json || true
cat /tmp/ndsep-ack-loss-initiation.json

printf '%s\n' '== Poll durable quarantine state =='
state=''
for ((i=1; i<=POLL_ATTEMPTS; i++)); do
  state="$(psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -Atc \
    "SELECT state FROM financial_transfer_outbox WHERE transfer_reference = '$TEST_TRANSFER_REFERENCE';")"
  printf 'poll=%s state=%s\n' "$i" "$state"
  [[ "$state" == reconciliation_required ]] && break
  sleep "$POLL_SECONDS"
done
[[ "$state" == reconciliation_required ]] || { echo 'FAIL: intent did not enter reconciliation_required' >&2; exit 1; }

printf '%s\n' '== Verify provider truth after lost acknowledgement =='
tb_json="$(curl --fail --silent --show-error --max-time 15 -H "authorization: Bearer $PROVIDER_LOOKUP_TOKEN" "$TIGERBEETLE_LOOKUP_URL/transfers/$TEST_TRANSFER_REFERENCE")"
mojaloop_status="$(curl --silent --show-error --max-time 15 -o /tmp/ndsep-mojaloop-lookup.json -w '%{http_code}' -H "authorization: Bearer $PROVIDER_LOOKUP_TOKEN" "$MOJALOOP_LOOKUP_URL/transfers/$TEST_TRANSFER_REFERENCE")"
printf 'tigerbeetle_lookup_received=true\nmojaloop_lookup_status=%s\n' "$mojaloop_status"
printf '%s\n' "$tb_json" | grep -Eq '"state"[[:space:]]*:[[:space:]]*"(committed|pending|aborted)"' || { echo 'FAIL: unrecognized TigerBeetle state' >&2; exit 1; }

printf '%s\n' '== Run reconciler through the approved operator endpoint/job =='
: "${RECONCILER_RUN_URL:?RECONCILER_RUN_URL is required for execute mode}"
curl --fail --silent --show-error --max-time 30 -X POST \
  -H "authorization: Bearer $PROVIDER_LOOKUP_TOKEN" \
  -H 'content-type: application/json' \
  --data "{\"transferReference\":\"$TEST_TRANSFER_REFERENCE\"}" \
  "$RECONCILER_RUN_URL" >/tmp/ndsep-ack-loss-reconcile.json
cat /tmp/ndsep-ack-loss-reconcile.json

final_state="$(psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -Atc \
  "SELECT state FROM financial_transfer_outbox WHERE transfer_reference = '$TEST_TRANSFER_REFERENCE';")"
provider_observations="$(psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -Atc \
  "SELECT count(*) FROM financial_provider_reconciliation WHERE transfer_reference = '$TEST_TRANSFER_REFERENCE';")"
printf 'final_state=%s provider_observations=%s\n' "$final_state" "$provider_observations"
[[ "$provider_observations" -ge 2 ]] || { echo 'FAIL: both provider observations were not recorded' >&2; exit 1; }
[[ "$final_state" != settled ]] || { echo 'FAIL: transfer settled before signed callback verification' >&2; exit 1; }
printf '%s\n' 'PASS: acknowledgment-loss gate completed without an unverified settlement.'
